Breeding-Insight/bi-api

- README.md
- Added license section to readme with FOSSA license badge (click to see full report)
- Scan was for latest on develop
- Not currently automatic, will need to rerun periodically or setup automated running in the future
- No dependency license issues found
> INF-164 - Validate package dependencies to make sure we don't have any GPL dependencies

- src/main/java/org/breedinginsight/api/v1/controller/UserController.java
- src/main/java/org/breedinginsight/services/UserService.java
- src/test/java/org/breedinginsight/api/v1/controller/UserControllerIntegrationTest.java
Adds a check to not allow the user to deactivate their own account. 
Is paired with ISSUE-5 PR in bi-web.
> prevent user from deactivating themselves

- docker-compose.yml
Updates docker-compose to reference the new brapi-server image.
> update brapi server reference

- .github/pr-labeler.yml
- .github/release-drafter.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-drafter.yml
Adding github actions for release drafter that were reviewed in the test-project.
> INF-202 - Development release notes and release drafter investigation 

- .env
- .github/workflows/build.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- Updated application.yml and application-prod.yml
> BI-299 - Update application-prod.yml to define the web host (instead of loginSuccess/loginFailure/logout)

- docs/openapi.yaml
- pom.xml
- src/main/java/org/breedinginsight/api/v1/controller/TraitController.java
- src/main/java/org/breedinginsight/daos/TraitDAO.java
- src/main/java/org/breedinginsight/services/TraitService.java
- src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java
- src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java
- src/main/java/org/breedinginsight/services/validators/TraitValidatorErrorInterface.java
- src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java
- src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
Add PUT traits to the backend. PUT traits accepts a list of traits. Also pushes the changes to the connected brapi server. 
Added a positive test for PUT traits. Needs a couple more negative traits. 
See other PRs:
https://github.com/Breeding-Insight/bi-web/pull/72
https://github.com/Breeding-Insight/sgn/pull/7
> [BI-677] - PUT traits

- docker-compose.yml
- src/main/java/org/breedinginsight/api/v1/controller/HttpStatusExceptionHandler.java
- src/main/java/org/breedinginsight/api/v1/controller/TraitUploadController.java
- src/main/java/org/breedinginsight/api/v1/controller/brapi/BrAPIServiceFilter.java
- src/main/java/org/breedinginsight/services/TraitUploadService.java
- src/main/resources/brapi/properties/application.properties
- src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
- src/test/resources/brapi/properties/application.properties
- BI-780 acceptance criteria passed
- BI-777 acceptance criteria passed
- BI-772 acceptance criteria passed, a little unsure about ordinal/nominal form thought there were supposed to be labels for ordinal
> BI-731 - Fix Issue #42 in BrAPI Test Server and Fix PUT traits unit/integration tests in bi-api

- src/main/java/org/breedinginsight/services/parsers/ParsingExceptionType.java
See bi-web change: 
https://github.com/Breeding-Insight/bi-web/pull/98
> [BI-986] - Add more description to scale min/max requirements in importer error

- src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationDAO.java
- src/main/java/org/breedinginsight/brapps/importer/model/base/Observation.java
- src/main/java/org/breedinginsight/brapps/importer/model/base/ObservationUnit.java
- src/main/java/org/breedinginsight/brapps/importer/model/base/Study.java
- src/main/java/org/breedinginsight/brapps/importer/model/imports/BrAPIImport.java
- src/main/java/org/breedinginsight/brapps/importer/model/imports/phenotyping/PhenotypingStudyWithDataImport.java
- src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java
- src/main/java/org/breedinginsight/brapps/importer/services/MappingManager.java
- src/main/java/org/breedinginsight/brapps/importer/services/processors/ObservationProcessor.java
- src/main/java/org/breedinginsight/brapps/importer/services/processors/ObservationUnitProcessor.java
- src/main/java/org/breedinginsight/brapps/importer/services/processors/StudyProcessor.java
- src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java
- src/main/java/org/breedinginsight/utilities/FileUtil.java
- Add additionalInfo support for Observations
- Add support for multiple observations per row
- Add Observation unit position / levels support
- Add Experimental Design PUI to study
- Some importer mapping bug fixes
> BI-969 - Blueberry Penetrometer Import

- src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java
- Added some logging to help debug when importer things go wrong
> QA Bug fixes

- src/main/resources/db/migration/V0.5.27__add_germplasm_template_system_mapping.sql
- src/test/java/org/breedinginsight/api/v1/controller/ImportControllerIntegrationTest.java
- Migration to add default system level germplasm template mapping
- Update validation tests to account for existing system mapping
Linked to PR [bi-web/BI-1176](https://github.com/Breeding-Insight/bi-web/pull/150)
> [BI-1176] Create Germplasm Template Mapping

- src/main/java/org/breedinginsight/brapi/v2/BrAPIV2Controller.java
- src/main/java/org/breedinginsight/brapi/v2/model/response/mappers/ListQueryMapper.java
- src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
- src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIListDAO.java
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1399
Added pagination to the list backend. 
biweb: BI-1399
sgn: BI-1399
See bi-web PR for details.
> [BI-1399] Fix list pagination

- src/main/resources/db/migration/V0.5.33__alter-breeding-methods.sql
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1397
Fixed breeding methods to match Shawn's specification. https://breedinginsight.atlassian.net/wiki/spaces/BI/pages/1554907145/Breeding+Methods+Validations
bi-web: BI-1397
1. Download the template from the germplasm import page and verify the changes in the JIRA card are reflected. 
2. Create a germplasm import that uses all of the breeding method codes and names from Shawn's specification: https://breedinginsight.atlassian.net/wiki/spaces/BI/pages/1554907145/Breeding+Methods+Validations
3. Import file and ensure there are no errors.
> [BI-1397] Breeding methods: update breeding method db entries

- src/main/java/org/breedinginsight/brapps/importer/model/base/Observation.java
- src/main/java/org/breedinginsight/brapps/importer/model/imports/phenotyping/PhenotypingStudyWithDataImportService.java
- src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java
- src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1386
Fixes the silent failure when the phenotypic brapi importer returns a ValidatorException. 
Add required annotations to fields in the brapi importer that are required. 
bi-web: BI-1386
Below are some files with different test scenarios that will show errors for the importer. Also included are files for the germplasm and traits importer to test that those errors still work. 
[BI_1373_TRAITS_good_traits.xls](https://github.com/Breeding-Insight/bi-api/files/8124752/BI_1373_TRAITS_good_traits.xls)
[BI-1386-bad-breeding-methods.xlsx](https://github.com/Breeding-Insight/bi-api/files/8124753/BI-1386-bad-breeding-methods.xlsx) …
> [BI-1386] Brapi importer: fix phenotyping importer

- src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIListDAO.java
**Story:** [BI-1412](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1412)
When the BrAPI call to `/lists` is made to Breedbase it ignores search queries involving externalReferences or externalSources. This will be fixed in Breedbase in a separate card. This card adds a check in bi-api to search for externalReferences and exxternalSources.
bi-web develop
import germplasm using the BI UI.  Click on the germplasm lists table. Only the imported list and any other lists imported via BI UI should be visible.  Any lists imported directly to Breedbase should be absent from the table.
> [BI-1412] ISSUE: Navigating to "Germplasm Lists" shows all germplasm lists that exist in Breedbase

- src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIListDAO.java
**Story:** [BI-1412](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1412)
When the BrAPI call to `/lists` is made to Breedbase it ignores search queries involving externalReferences or externalSources. This will be fixed in Breedbase in a separate card. This card adds a check in bi-api to search for externalReferences and exxternalSources.
bi-web develop
import germplasm using the BI UI.  Click on the germplasm lists table. Only the imported list and any other lists imported via BI UI should be visible.  Any lists imported directly to Breedbase should be absent from the table.
https://github.com/Breeding-Insight/taf/actions/runs/2065446280
> add method to check externalReferences of BrAPI lists

- src/main/resources/db/migration/V0.7.1__add_breeding_methods.sql
**Story:** 
[BI-1491 - New Breeding Method - Polyembryonic seed selection](https://breedinginsight.atlassian.net/browse/BI-1491)
[BI-1527 - New Breeding Method - Creation of triploids by applied pressure or temperature shock](https://breedinginsight.atlassian.net/browse/BI-1527)
[BI-1528 - New Breeding Method - Creation of tetraploids by applied pressure shock](https://breedinginsight.atlassian.net/browse/BI-1528)
Added 3 new breeding methods to germplasm import template
Created flyway migration to add the new breeding methods to breeding methods table
[bi-web: feature/BI-1494](https://github.com/Breeding-Insight/bi-web/pull/250)
see bi-web
> [BI-1491] [BI-1527] [BI-1528] Add more breeding methods

- src/main/java/org/breedinginsight/brapi/v2/ExperimentController.java
- src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java
- src/main/java/org/breedinginsight/brapps/importer/daos/BrAPITrialDAO.java
- src/main/java/org/breedinginsight/utilities/response/mappers/ExperimentQueryMapper.java
**Story:** [BI-1198 - All Experiments Table](https://breedinginsight.atlassian.net/browse/BI-1198)
Added /trial endpoint for Experiments and Observations table
Added ExperimentController.java, BrAPITrialService.java, and ExperimentQueryMapper.java
Modified BrAPITrialDAO and added getTrials and processExperimentsForDisplay methods
[bi-web/BI-1198-2](https://github.com/Breeding-Insight/bi-web/pull/254)
see bi-web
> [BI-1198] All Experiments Table

- src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java
**Story:** _Please include a link to the story in Jira_
_Please include a summary of the change that was made._
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._
_Please include any details needed for reviewers to test this code_
> BI-1844 - Experiments & Observations file import didn't recognize the word TEST or CHECK

- src/main/resources/brapi/properties/application.properties
- src/main/resources/brapi/sql/create_indexes.sql
- src/main/resources/brapi/sql/species.sql
Per [Nick's suggestion](https://github.com/Breeding-Insight/brapi-Java-TestServer/pull/11#discussion_r1291523500) on https://github.com/Breeding-Insight/brapi-Java-TestServer/pull/11.
See [my comment below](https://github.com/Breeding-Insight/bi-api/pull/283#issuecomment-1678082335) to understand the changes to application.properties.
> [BI-1771] - added create_indexes.sql

- src/main/resources/brapi/sql/species.sql
- src/main/resources/db/migration/V0.5.36__add-new-species.sql
**Story:** https://breedinginsight.atlassian.net/browse/BI-1956?atlOrigin=eyJpIjoiOTQ0N2JjZjQxYzE4NDU0YTljZTFjODEzMjI3ZjJmZTEiLCJwIjoiaiJ9
- Added sorghum and hemp species to bi & brapi server\
- Also added brapi species in docker stack https://github.com/Breeding-Insight/bi-docker-stack/pull/33
-None
- Verify new species exist in program select box
- Verify a new program saves to the brapi server without error using one of the new species
> BI-1956 - Add sorghum and hemp species migration

- src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-2064](https://breedinginsight.atlassian.net/browse/BI-2064) Invalid message if required data is missing 
Not conforming
bi-web: release/0.9
see **Acceptance Criteria**in the [Jirra Ticket](https://breedinginsight.atlassian.net/browse/BI-2064)
[BI-2026]: https://breedinginsight.atlassian.net/browse/BI-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2064]: https://breedinginsight.atlassian.net/browse/BI-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BI-2064] Invalid message if required data is missing 

- src/main/resources/brapi/sql/R__species.sql
**Story:** BI-2163
- Added species to brapi server that were missing
- None
- Create a program using one of the new species from the program creation page, make sure it creates it without error
> BI-2163 QA Failure

- src/main/java/org/breedinginsight/utilities/FileUtil.java
See the [original PR](https://github.com/Breeding-Insight/bi-api/pull/416) for details. (Jira story: https://breedinginsight.atlassian.net/browse/BI-2338)
> BI-2338 - merging into develop
