src/main/java/org/breedinginsight/api/model/v1/response/DataResponse.java, src/test/java/org/breedinginsight/api/v1/controller/ProgramControllerIntegrationTest.java
One Line of code to fix it all, One line to find them,
One Line of code to bring them all and in the Jackson bind them
- Tests run
- Data object is in the result of the response even if not results are returned.
=> INF-138 - Include data in response even if not populated

src/main/java/org/breedinginsight/model/ProgramLocation.java, src/main/java/org/breedinginsight/services/ProgramLocationService.java, src/test/java/org/breedinginsight/api/v1/controller/ProgramControllerIntegrationTest.java
The trello card explains it all, 
https://trello.com/c/03b8Z0jy/167-pro-77-bug-post-locations-controller-inserts-null-into-sql-column-when-there-is-no-data
- Made bi-api insert NULL into db when coordinates are not passed in. 
- Made bi-api not error out when reading NULL for coordinates from DB
=> insert [NULL] into db when coordinates not specified

.github/workflows/build.yml, docker-compose.yml, src/main/java/org/breedinginsight/api/auth/AuthServiceLoginHandler.java, src/main/java/org/breedinginsight/daos/TraitDAO.java, src/main/java/org/breedinginsight/services/TraitService.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/test/java/org/breedinginsight/api/auth/AuthServiceLoginHandlerUnitTest.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java, src/test/java/org/breedinginsight/services/validators/TraitValidatorIntegrationTest.java, src/test/resources/sql/TraitControllerIntegrationTest.sql
Fixes a bug where the trait duplicate checks were checking against the whole database. The check should be within a program. 
Added a test for the bug as well. 
Also includes a fix for the tests where `AuthServiceLoginHandlerUnitTest` was polluting tests that came after it by manually setting the current request on `ServerRequestContext`.
=> [ISSUE-9] Make traits duplicate check within the program

src/main/resources/db/migration/V0.5.15__create-inventory-tables.sql
- generated sql from inventory dbml specification
- added our id and create/edit tracking
- renamed cross table to entity_cross due to cross being a reserved postgres keyword
- changed a few types from the generated sql, datetime -> timestamptz(0), geojson -> jsonb
- gave active boolean fields default of true
- didn't change add/change any of the not null specifications
- `mvn validate flyway:clean flyway:migrate -X --settings settings.xml` runs without error
- `mvn clean generate-sources --settings settings.xml` runs without error
=> BI-256 - Define inventory database schema

docs/openapi.yaml, src/main/java/org/breedinginsight/api/v1/controller/TraitUploadController.java, src/main/java/org/breedinginsight/model/ProgramUpload.java, src/main/java/org/breedinginsight/services/TraitUploadService.java, src/main/java/org/breedinginsight/utilities/response/ResponseUtils.java, src/test/java/org/breedinginsight/api/v1/controller/TraitUploadControllerIntegrationTest.java
Updated trait upload services to parse the JSONB data from the database before returning to controller. For the sorting/filtering/pagination we needed something we could read and act on, so that seemed like the most logically course. It doesn't change the way the data is returned. 
There is one more point of failure in the upload process though. If for some reason the data was not stored properly during the file upload, there will be a failure when parsing this. But, that should never happen since the JSONB being stored in the database is rendered from Trait objects to begin with.
=> [BI-617] - Sort/paginate/filter for trait upload

src/main/java/org/breedinginsight/api/auth/AuthServiceLoginHandler.java, src/main/resources/application.yml
Fixes issue with the nonce token (a token in the openid handshake that identifies a request upon return to open id requestor) expiring during the login process. The token still expires, but a bad token validation is handled and the user is notified on the front page to try again. I increase the expiration time to 10 minutes (it was 5 minutes). 
I also included a way to log out of open id before beginning the login process. This should be able to handle any Open ID provider if they have a logout URI. The logout url isn't required, and the process skips over that part if the logout attempt fails, or if the url isn't provided in the config. 
https://github.com/Breeding-Insight/bi-web/pull/50
1. Try changing the cookie expiration to 1s and check that you get the right page (see below)
2. Try …
=> [BI-626] - Handle login timeout error

src/main/resources/brapi/properties/application.properties
the `ddl-auto` setting was set to create a new database schema on startup, and drop on shutdown.  Changed the setting value to only update on startup, and nothing on shutdown.
=> Changing startup/shutdown action to prevent wiping of database

src/main/java/org/breedinginsight/api/v1/controller/brapi/BrAPIServiceFilter.java, src/main/java/org/breedinginsight/daos/ProgramDAO.java, src/main/java/org/breedinginsight/services/ProgramService.java, src/main/java/org/breedinginsight/services/brapi/BrAPIProvider.java, src/test/java/org/breedinginsight/api/v1/controller/ProgramControllerIntegrationTest.java, src/test/resources/sql/ProgramControllerIntegrationTest.sql, src/test/resources/sql/TraitControllerIntegrationTest.sql
Creates brapi program on program create. Updates brapi program on program update. 
When the program is created, it is posted to the default brapi service. When we add the functionality to allow the program to sync with their own brapi service, the program and all other existing data will need to be created in that service. 
I did some rework on the program integration tests because the brapi integration broke a lot of them. Some general clean up is also included because those tests are a pain to use and debug.
=> [BI-280] - Add brapi program create and update on program create and update

docs/openapi.yaml, src/main/java/org/breedinginsight/api/deserializer/ArrayOfStringDeserializer.java, src/main/java/org/breedinginsight/api/deserializer/ListOfStringDeserializer.java, src/main/java/org/breedinginsight/api/deserializer/StringDeserializer.java, src/main/java/org/breedinginsight/api/v1/controller/ProgramController.java, src/main/java/org/breedinginsight/api/v1/controller/TraitController.java, src/main/java/org/breedinginsight/api/v1/controller/TraitUploadController.java, src/main/java/org/breedinginsight/brapi/v1/services/BrapiObservationVariableService.java, src/main/java/org/breedinginsight/daos/TraitDAO.java, src/main/java/org/breedinginsight/model/ProgramUpload.java, src/main/java/org/breedinginsight/model/Trait.java, src/main/java/org/breedinginsight/services/ProgramObservationLevelService.java, src/main/java/org/breedinginsight/services/ProgramService.java, src/main/java/org/breedinginsight/services/TraitService.java, src/main/java/org/breedinginsight/services/TraitUploadService.java, src/main/java/org/breedinginsight/services/parsers/trait/TraitFileParser.java, src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorErrorInterface.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/main/resources/application.yml, src/main/resources/brapi/sql/species.sql, src/main/resources/db/migration/V0.5.18__remove_code_data_type.sql, src/test/java/org/breedinginsight/api/v1/controller/ProgramControllerIntegrationTest.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java, src/test/java/org/breedinginsight/api/v1/controller/TraitUploadControllerIntegrationTest.java, src/test/resources/sql/ProgramControllerIntegrationTest.sql, src/test/resources/sql/UploadControllerIntegrationTest.sql, src/test/resources/sql/brapi/species.sql
Some fixes to allow POST traits to work directly from the UI. 
Added an optional deserializer for List<String> and String[] to remove blank strings and nulls from incoming lists. I couldn't figure out how to get it to happen for every List<String>, so I stuck with this method. There is a deserializer for all incoming strings that trims them and replaces them with null if they are blank. 
The trait upload now saves traits by POSTing a confirmation to the trait upload controller, which gets the json from the db and saves that. I could have done this without requiring the upload ID, but having the upload ID makes it more stateless because you are acting on a specific resource. 
Mixes in a bit of BI-686 in this one. I was working on these at the same time so there is a bit of overlap.
=> [BI-85,BI-646] - POST traits from UI

docs/openapi.yaml, src/main/java/org/breedinginsight/daos/TraitDAO.java, src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
Changes unique trait check to be determined on by trait name. 
Updates to the validation errors so that you can indefinitely nest errors. This was needed to parse errors for specific categories. Here is an example of the new error format:
=> [BI-685] - Map backend trait validation errors to front end

docs/openapi.yaml, src/main/java/org/breedinginsight/api/v1/controller/TraitController.java, src/main/java/org/breedinginsight/daos/TraitDAO.java, src/main/java/org/breedinginsight/services/TraitService.java, src/main/resources/db/migration/V0.5.19__set_trait_active.sql, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
Sets trait to active/inactive in our system. Sends `archived` or `active` through brapi's `variable.status` field. 
Need to add tests still and update the docs.
=> [BI-732,BI-729] - Archive traits

.env
BRAPI_CORE_URL=http://brapiserver:8080
BRAPI_PHENO_URL=http://brapiserver:8080
BRAPI_GENO_URL=http://brapiserver:8080
EMAIL_RELAY_HOST=mailhog
=> [BI-714] .env variables in default file are out of date

pom.xml, src/main/java/org/breedinginsight/brapi/v1/controller/BrapiAuthorizeController.java, src/main/java/org/breedinginsight/brapi/v2/BrAPIV2Controller.java, src/test/java/org/breedinginsight/BrAPITest.java, src/test/java/org/breedinginsight/brapi/v1/controller/BrapiAuthorizeControllerIntegrationTest.java, src/test/java/org/breedinginsight/brapi/v2/BrAPIV2ControllerIntegrationTest.java
Created a BrAPI v2 controller that has catchall methods to intercept GET, PUT, and POST requests to BrAPI endpoints, scoped within a program.  BrAPI endpoints are of the form `/v1/programs/{programId}/brapi/v2/<BrAPI endpoint>`.
There is a `serverinfo` endpoint that is at the root of bi-api (`/brapi/v2/serverinfo`), with basic server information.
=> BI-741 - Create BrAPI v2 Proxy

src/main/java/org/breedinginsight/brapi/v2/BrAPIV2Controller.java
- Changed the proxy endpoints to accept `HttpRequest<byte[]>`. It works the same, but this allows us to pass images through. 
- Passed through `Content-Type` through the proxy
- Fixed a bug that didn't account for `/brapi/v2` on the end of custom endpoints. 
- Broke up the proxy code a little more so I could reuse it for the `executeRequest` method and the new `executeByteRequest` method.
=> [BI-763] Updates to brapi v2 proxy to support Field Book

src/main/java/org/breedinginsight/brapps/importer/services/ImportStatusService.java
Switched to json for mapping serialization to handle the switch to JsonObjects in the brapi client objects.
=> Fix json serialization issue in import mapping due to change in brapi client

src/main/java/org/breedinginsight/brapps/importer/model/base/Study.java
Breedbase `POST /studies` requires the studyType field to be set so adding it as a required field to the importer for the Study object.
=> Importer add studyType to Study

src/main/java/org/breedinginsight/daos/TraitDAO.java
The real fix to this was to update the reltest brapi server database. This fix is to make it so that there is a bug that returns something like:
```
additionalInfo: {
tags: null
}
```
from the brapi-server again, it won't prevent the user from seeing their list of traits.
=> [BI-1223] Add null check for tags field

src/main/resources/db/migration/V0_5_29__add_program_keys.sql
Due to the new required program Key field, a migration is needed to add keys to existing programs.
NOTE: This migration just adds a value for the key column in the bidb programs table. Once this migration is run, the programs will need to be saved on the BI UI to have the keys associated with the name in the brapi database.
=> [BI-1227] Add 'Program Key' to Existing Programs

src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
Germplasm were being POSTed twice because of bug in the post order construction. 
See sgn BI-1251 for card details: https://github.com/Breeding-Insight/sgn/pull/48
=> [BI-1251] - Germplasm import: fix to post order construction

src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/resources/db/migration/V0.5.32__germplasm_import_change_dbid_to_gid.sql, src/test/resources/files/germplasm_import/bad_breeding_methods.csv, src/test/resources/files/germplasm_import/circular_parent_dependencies.csv, src/test/resources/files/germplasm_import/duplicate_entry_numbers.csv, src/test/resources/files/germplasm_import/empty_required_fields.csv, src/test/resources/files/germplasm_import/empty_values_required_fields.csv, src/test/resources/files/germplasm_import/female_dbid_not_exist.csv, src/test/resources/files/germplasm_import/female_entry_number_not_exist.csv, src/test/resources/files/germplasm_import/full_import.csv, src/test/resources/files/germplasm_import/male_dbid_no_female_success.csv, src/test/resources/files/germplasm_import/male_dbid_not_exist.csv, src/test/resources/files/germplasm_import/male_entry_number_not_exist.csv, src/test/resources/files/germplasm_import/minimal_germplasm_import.csv, src/test/resources/files/germplasm_import/missing_optional_header.csv, src/test/resources/files/germplasm_import/missing_required_header.csv, src/test/resources/files/germplasm_import/no_female_parent_blank_pedigree.csv, src/test/resources/files/germplasm_import/nonnumerical_entry_numbers.csv, src/test/resources/files/germplasm_import/self_ref_parent_dependencies.csv, src/test/resources/files/germplasm_import/some_entry_numbers.csv
**Story:** (https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1219)
Updated the germplasm system import to accept "Parent GID" for column instead of "Parent DB ID". The BrAPI Importer was already updated so that did not needed any changes. 
I also needed to update the Germplasm Import test files to reflect the column header change.
biweb: BI-1219 (https://github.com/Breeding-Insight/bi-web/pull/166)
See biweb: BI-1219 for testing details.
=> [BI-1219] Update Germplasm Import Parent DBID to GID

src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
There is a bug with dsl.nextval() that gets our germplasm sequence values where it surrounds program keys that aren't lowercased with quotes, select nextval('"program_sequence"'). This causes a not found error in psql. 
none
Uppercase the program key in one of your germplasm sequences. For example, change bb_germplasm_sequence to BB_germplasm_sequence.
=> [BI-1315] germplasm import: fix next val germplasm sequence call

pom.xml, src/main/java/org/breedinginsight/brapi/v2/dao/ProgramCache.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmTemplateMap.java, src/test/resources/files/germplasm_import/duplicate_db_names.csv
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1149
- Uses the import object state (EXISTING) to mark potential duplicates in the germplasm import. 
- Doesn't indicate the reason for the duplicate marking, but since name is our only reason right now that isn't a current issue. 
- If we need more details in the future we can add a `warnings` field that looks like our multiple error return. 
- Added tests
bi-web: BI-1149
See bi-web branch for testing
=> [BI-1149] Highlighting duplicate germplasm

src/main/java/org/breedinginsight/brapps/importer/model/ImportProgress.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/BrAPIImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/germplasm/GermplasmImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorManager.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmTemplateMap.java
**Story:**  [Story: BI-1074 - 1.4 Germplasm Import - Validate Breeding Methods](https://breedinginsight.atlassian.net/browse/BI-1074)
When Importing Germplasms, validate the breading methods against the breeding_method table.
Must be run with bi-web branch feature/BI-1074.
- [ x] I have performed a self-review of my own code
- x[ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [x ] I have commented my code, particularly in hard-to-understand areas
=> [BI-1074 ] Add multiple error display and breeding method errors for germplasm import

src/main/java/org/breedinginsight/utilities/response/mappers/TraitQueryMapper.java, src/test/java/org/breedinginsight/TestUtils.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1370
Add traitDescription to the trait controller sort/filtering. 
bi-web: BI-1370
You can use this file to load some traits into your system if you need them. 
[BI_1373_good_traits.xls](https://github.com/Breeding-Insight/bi-api/files/8089829/BI_1373_good_traits.xls)
=> [BI-1370] ontology search: add trait description sorting

src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java, src/test/java/org/breedinginsight/api/v1/controller/TraitUploadControllerIntegrationTest.java, src/test/java/org/breedinginsight/services/validators/TraitValidatorUnitTest.java
**Story:** [BI-1281](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1281)
trait import validation error messages for observation variable names were changed to refer instead to "name"
bi-web `develop`
try importing a trait with a name that exceeds the 12 char limit.
=> [BI-1281] refactor obsVarName error messages to use Name

pom.xml, src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/ProgramCache.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java, src/main/java/org/breedinginsight/utilities/Utilities.java, src/test/java/org/breedinginsight/brapi/v2/ProgramCacheUnitTest.java, src/test/java/org/breedinginsight/services/BrAPIGermplasmServiceUnitTest.java, src/test/resources/logback.xml
https://breedinginsight.atlassian.net/browse/BI-1408
Refactored the germplasm cache to store the processed germplasm that bi-api will return instead of the raw germplasm that came from the BrAPI service storing the program's data.
bi-web - release/0.5
_Please include any details needed for reviewers to test this code_
=> BI-1408 - ISSUE - All Germplasm Table stuck loading when connected with Breedbase

src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1291?atlOrigin=eyJpIjoiMjg3MTc1YWQzMjA3NDQyMTgyMzliNGFmNjJhYmM4ZWUiLCJwIjoiaiJ9
- Added parental gids and entry numbers to additionalInfo to facilitate display on front end
- BI-1291 on bi-web
- Import germplasm file with parents specified as both gids and entry numbers and verify they are displayed correctly on the bi-web germplasm import preview page. Also verify that the External UID works.
=> BI-1291 - Import Germplasm Preview Columns Incorrect

src/main/java/org/breedinginsight/brapps/importer/model/base/Observation.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ObservationProcessor.java
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1435
Changed the observation hashing in the importer to allow for null observation dates. Made observation date optional. 
sgn: BI-1435
biweb: release/0.5
1. Create an import with observation dates for the file below. 
2. Import that file, see that the observations are labeled NEW
3. Import that file again, they should now be EXISTING.
4. Create an import with no observation date mapped. 
5. Import the same file, see that observations are labeled as NEW
6. Import the file again, see that the observations are label as EXISTING. 
[phenotypic_importer_demo.xlsx](https://github.com/Breeding-Insight/bi-api/files/8289362/phenotypic_importer_demo.xlsx)
=> [BI-1435] Allow for null observation dates

src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
**Story:** [4.3 Germplasm List Export File - FAILED QA](https://breedinginsight.atlassian.net/browse/BI-1088)
- Fixed pedigree logic to check for empty string as well as null
bi-web/release/0.5
See https://github.com/Breeding-Insight/bi-api/pull/162
- [n/a] I have create/modified unit tests to cover this change
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to documentation
- [] I have run TAF: _\<link to TAF run>_
=> [BI-1088] Germplasm Export QA Fix 2

src/main/java/org/breedinginsight/daos/TraitDAO.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
**Story:** [BI-1365](https://breedinginsight.atlassian.net/browse/BI-1365?atlOrigin=eyJpIjoiNzk2ZWNjZmM2OGM2NDU4YThkN2M4NmI2NzdhZjUzNzkiLCJwIjoiaiJ9)
- Added program key to scope ontology terms
None
- Create and update ontology terms. Verify that the observationVariableName, traitName, scaleName, and methodName values are scoped with the program key in the underlying brapi service and that these fields all appear normal without the program key in the BI interface.
=> BI-1365 - Scope ontology terms to be within a program when saved over BrAPI

src/main/java/org/breedinginsight/api/v1/controller/OntologyController.java, src/main/java/org/breedinginsight/api/v1/controller/TraitController.java, src/main/java/org/breedinginsight/api/v1/controller/TraitUploadController.java, src/main/java/org/breedinginsight/services/OntologyService.java, src/main/java/org/breedinginsight/services/exceptions/BadRequestException.java
**Story:** [BI-1364 View a shared ontology that a program is subscribed to](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1364)
A new exception class for returning 400 status was created.
OntologyService methods were created that wrap around existing TraitService and TraitUploadService methods which use the program ID for the case of a non-subscriber or sharing program and the sharing program's ID in the case of a subscribed program.
TraitController and TraitUpload controller were updated to return 400 status if a subscribed program requests to create or update traits of a shared ontology.
bi-web BI-1364 branch
See testing procedure for biweb BI-1364.
In addition, manually try to create and update traits for a subscribing program …
=> [BI-1364] View a shared ontology that a program is subscribed to

src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java, src/test/java/org/breedinginsight/services/validators/TraitValidatorUnitTest.java
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1446
The trait errors were accidentally changed when making the trait file import names more consistent. (https://github.com/Breeding-Insight/bi-api/pull/150/files#diff-645879ab06ebc8d8a2f7b0272aaf4c5e897cb743c52798982139924349f1235f)
Reversed those changes for the trait form code, but kept the fixes to the trait file import code. 
biweb: develop
1. Go to the trait list
2. Click on "New Trait"
3. Check that the errors are displayed below the fields. 
4. Try out the Computation, Ordinal, and Nominal fields.
=> [BI-1446] trait error: fix error display on trait form

src/main/java/org/breedinginsight/daos/TraitDAO.java, src/main/java/org/breedinginsight/services/TraitService.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
**Story:** [BI-1445 - Trait Column value not the same as entered in the the Term creation](https://breedinginsight.atlassian.net/browse/BI-1445)
Implemented changes to make capitalization of trait entity, trait attribute, and method description more consistent in table and sidepanel display.
- On ontology term creation, set brapi trait entity to program observation level name to be consistent with ontology term update
- Modified saving of program observation level (and by extension trait entity) to capitalize each word rather than only the first letter
[bi-web/BI-1445](https://github.com/Breeding-Insight/bi-web/pull/240)
see bi-web for testing
=> [BI-1445] - Trait Entity/Attribute/Method capitalization

src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
**Story:** [BI-1224 - Show list creator in Germplasm lists table](https://breedinginsight.atlassian.net/browse/BI-1224)
Retrieves list creator and displays for germplasm lists.
As the brapi listOwnerName is not stored in breedbase, the list creator is retrieved from the first germplasm in the list, which requires multiple calls to retrieve alas. Trying to store listOwnerName in additionalInfo on list create does not work alas as additionalInfo for lists is also not saved on breedbase.
[bi-web/BI-1224](https://github.com/Breeding-Insight/bi-web/pull/244)
see bi-web
=> [BI-1224] - Show list creator in Germplasm lists table

src/main/java/org/breedinginsight/api/model/v1/request/query/SearchRequest.java, src/main/java/org/breedinginsight/brapi/v1/model/request/query/BrapiQuery.java, src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapi/v2/model/request/query/GermplasmQuery.java, src/main/java/org/breedinginsight/brapi/v2/model/response/mappers/GermplasmQueryMapper.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java, src/main/java/org/breedinginsight/utilities/response/ResponseUtils.java, src/main/java/org/breedinginsight/utilities/response/mappers/FilterField.java, src/test/java/org/breedinginsight/brapi/v2/GermplasmControllerIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1191
- Added `POST search/germplasm` and filters to `GET /germplasm`. 
- Added tests for germplasm filtering. 
- Replaced a bunch of germplasm additional info strings with constants. 
biweb: BI-1191
1. Upload some germplasm
2. Try out the filters
3. Check the debounce time, accuracy of results, multiple search behavior, how it works with pagination.
=> [BI-1191] Germplasm Search

src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/resources/db/migration/V1.0.2__update_experiment_template_system_mapping.sql
**Story:** 
1146 failed QA. The failure was `Acceptance 1. The experiment import template still has a column for “Exp Trt Factor Name” instead of “Treatment Factors”.`
Updated template.  Updated display column name
bi-web branch bug/BI-1146
1. Upload an Experiment with the column **Exp Trt Factor Name**.  It should fail.
2. Upload an Experiment with the column **Treatment Factors**.  It should succeed.
=> [BI-1146] change ‘Exp Trt Factor Name’ to ‘Treatment Factors’ - failed QA

src/main/java/org/breedinginsight/brapps/importer/daos/BrAPISeasonDAO.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
While testing [BI-1189](https://breedinginsight.atlassian.net/browse/BI-1189), a bug was discovered.  If importing data for an existing study (on an existing experiment), the **Env Year** was displaying incorrectly in the table of the confirmation screen.  It would display the Session DbId instead of the year string.
bi-web develop-branch
1. Import and confirm _Experiments and Observations_ data from a flat file.
2. Import _Experiments and Observations_ data from the _same_ flat file (you should now be on the confirmation page).
**Expected results**
The data in the  **Env Year** on the confirmation page's table should match the data from the flat file.
=> [BI-1189] bug - Season dbId is displayed instead of year for the Env Year of existing studies.

src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/model/BrAPIConstants.java
**Story:** [BI-1574](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1574)
A typo was fixed in the BrAPIConstants class.
A REPLICATE enum in the ExperimentObservation class was replaced where BLOCK was needed, instead.
bi-web develop branch
import an experiment and check that the "Exp Block #" column in the preview table is the same as in the excel file.
=> [BI-1574] Exp Block # not displayed

src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/resources/application.yml
**Story:** [BI-1230 - Truly Unknown Germplasm](https://breedinginsight.atlassian.net/browse/BI-1230)
Updates to support importing germplasm with truly unknown parents without using a dummy parent. This development also ensures that unrelated germplasm with unknown parents are not falsely attributed as siblings in the pedigree view display.
This included adding GET endpoint calls to /pedigree and /progeny in GermplasmController and adding additionalInfo items of femaleParentUnknown and maleParentUnknown on import. For import and display, the GID of an Unknown Parent is 0, but the backend endpoint retrieval labels an unknown parent GID as <child GID>-F-Unknown or <child GID>-M-Unknown, which is needed for maintaining information of pedigree connections for constructing the pedigree tree.
To …
=> [BI-1230] Truly Unknown Germplasm

src/main/java/org/breedinginsight/brapi/v2/model/request/query/GermplasmQuery.java, src/main/java/org/breedinginsight/brapi/v2/model/response/mappers/GermplasmQueryMapper.java
**Story:** [BI-1478 - Add Pedigree to All Germplasm Table](https://breedinginsight.atlassian.net/browse/BI-1478)
Backend logic to support All Germplasm table sorting by additionalInfo.pedigreeByName.
[bi-web/feature/BI-1478](https://github.com/Breeding-Insight/bi-web/pull/271)
see bi-web
=> [BI-1478] - Add Pedigree to All Germplasm Table

src/main/java/org/breedinginsight/brapps/importer/model/imports/BrAPIImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/germplasm/GermplasmImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/Processor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorManager.java, src/main/resources/db/migration/V1.0.5__experiment_template_obsUnitID.sql
**Story:** [BI-1590 - Disallow Adding New Observation Unit to Existing Environment](https://breedinginsight.atlassian.net/browse/BI-1590)
Added logic to check for an experiment import row with an Env that already existed and no ObsUnitId (implying that a new ObsUnit should be created for an existing Environment), and if so, throw an error that displays in the banner.
In addition, fixed file mapping for experiment import template so ObsUnitId could actually be retrieved for said logic.
Note that this change just checks for existence of values in ObsUnitId column and does not do any validation on said column.
bi-web/develop
- Import experiment
- Try to upload another experiment with same environment as first and ObsUnitId column missing values - error in banner should appear
- Try to upload …
=> [BI-1590] - Disallow Adding New Observation Unit to Existing Environment

src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java, src/test/java/org/breedinginsight/daos/BrAPIDAOUtilUnitTest.java
**Story:** [BI-1580](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1580)
The page size used by bi-api when POSTing a search for a BrAPI variable was hard-coded to a value large enough to ensure that all records for the BrAPI variable would fit in a single page. This work-around ensures that when Breedbase returns a 202 response to the initial POST search the GET search will apply to all records of the BrAPI variable stored in Breedbase.
This change is a work-around until either Breedbase or the BrAPI spec is updated.
A unit test was created to test the search method using both the POST search callback and GET search callback.
none
run the unit test for BrAPIDAOUtil.search(), …
=> [BI-1580] BrAPIDAOUtils pagination only fetching first page of results

src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
**Story:** [BI-1147](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1147)
The ExperimentProcessor was changed to pass user information when committing a new trial brapi object to the database and the ExperimentObservation model was updated to write createdBy and createdDate into additionalInfo.
bi-web BI-1147 branch
import an experiment and re-import experiment with different environments. Verify the preview reponse from the bi-api server contains a trial brapi object that has a createdBy object and createdDate field assigned to additinalInfo.
=> [BI-1147] ﻿﻿2.0 Experimental Data Preview Universal Elements

src/main/java/org/breedinginsight/services/OntologyService.java
**Story:** [BI-1630 - De-activated programs still visible on Shared Ontology](https://breedinginsight.atlassian.net/browse/BI-1630)
Change a getAll to getActive call in order to retrieve only active programs for sharing ontology.
bi-web/develop
Create programs of the same species and storage
Deactivate one program
Check that only active programs show when clicking Share Ontology under Program Management > Configuration
=> [BI-1630] - De-activated programs still visible on Shared Ontology

src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/model/request/query/GermplasmQuery.java, src/main/java/org/breedinginsight/brapi/v2/model/response/mappers/GermplasmQueryMapper.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
**Story:** [BI-1129](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1129)
- a GET endpoint was added to `brapi/v2/GermplasmController.java` with the signature `programs/<program-ID>/germplasm/lists/<list-ID>/records`
- `/brapi/v2/services/BrAPIGermplasmService.getGermplasmByList()` created to fetch germplasm records in a list
none
Send a GET request `/v1/programs/<program-id>/germplasm/lists/<list-id>/records?sortField=importEntryNumber&sortOrder=ASC&page=0&pageSize=50`
and verify the response contains all germplasm records stored for the given program and list ID.
=> [BI-1129] View Germplasm List

src/main/java/org/breedinginsight/brapps/importer/model/ImportUpload.java, src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/FileMappingUtil.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorManager.java, src/main/java/org/breedinginsight/utilities/FileUtil.java, src/main/resources/db/migration/V1.0.9__add_dynamic_column_storage.sql, src/main/resources/version.properties, src/test/java/org/breedinginsight/brapi/v2/ProgramCacheUnitTest.java
**Story:** [BI-1194 - Upload with timestamps](https://breedinginsight.atlassian.net/browse/BI-1194)
Changes to Experiment Import to enable import and preview display of timestamps associated with phenotypes.
- Updated excel parsing to distinguish between date and numeric values
- Updated csv parsing to interpret dates as strings due to jackson messily converting LOCAL_DATE/LOCAL_DATETIME
- Added changes to pass list of ordered dynamic column names for display (since ordering lost in jsonb conversion to object)
- Added migration to store dynamic column names in importer_import table
- Added validation for timestamp column names and values
- Updated storing of observations to add corresponding timestamp if present
[bi-web/BI-1194](https://github.com/Breeding-Insight/bi-web/pull/281)
see …
=> [BI-1194] - Upload with timestamps

src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmTemplateMap.java, src/test/resources/files/germplasm_import/no_female_parent_blank_pedigree.csv
**Story:** https://breedinginsight.atlassian.net/browse/BI-1683
Added a validation to check if a female parent is provided when only a male parent is provided.  Also allowing only a male parent to be saved when persisting to the BrAPI server
SGN - https://github.com/Breeding-Insight/sgn/pull/94
[Germ_BI-1683.xls](https://github.com/Breeding-Insight/bi-api/files/10290484/Germ_BI-1683.xls)
The attached file has two germplasm records with only a male parent defined (and `0` for the female parent).
- Upload a file with only a male parent defined and no female parent defined.  Ensure an error is returned stating a female parent must be defined
- Upload a file with a male parent defined, and a female parent of `0`.  Ensure the preview works, and then you are able to confirm the import.  After …
=> BI-1683 - Missing female parent in biparental cross results in dropped male parent v0.7

src/main/java/org/breedinginsight/model/Trait.java, src/main/java/org/breedinginsight/services/TraitService.java, src/main/java/org/breedinginsight/utilities/response/mappers/TraitQueryMapper.java, src/main/resources/db/migration/V1.0.10__add_onto_term_type.sql
**Story:** [BI-1615 - Add termType to Trait DB Table](https://breedinginsight.atlassian.net/browse/BI-1615)
Created migration to create term_type enum in backend and a term_type column in the trait table and populate said column with default of "PHENOTYPE"
Added support to save/update values to term_type in backend
[bi-web/BI-1615](https://github.com/Breeding-Insight/bi-web/pull/285)
see bi-web
=> [BI-1615] - Add termType to Trait DB Table

docs/openapi.yaml, src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java
**Story:** [_Please include a link to the story in Jira_](https://breedinginsight.atlassian.net/browse/BI-1440?atlOrigin=eyJpIjoiZmRjZDRmMWMzNzJhNDhjMGJhMzlhYzY4ZDU4YTYzZmEiLCJwIjoiaiJ9)
- Changed scale datatype to scale class in message
- bi-web develop
- Follow process in JIRA card and verify error message is as expected.
=> BI-1440 - ISSUE: ERROR message in banner calls out "scale data type" when field is "scale class"

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/model/Trait.java, src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java
[BI-1665](https://breedinginsight.atlassian.net/browse/BI-1665)
sgn:  feture/BI-1665 branch
bi-web: develop branch
in your _sgn_local.conf_ add the key-value pair:
`brapi_observations_require_login 0`
1. Import an Experiments & Observation file with at least one phenotype column with the corresponding timestamp column(s).
2. Confirm the import.
3. Insure that the data has been saved in he backing BrAPI server  
[BI-1665]: https://breedinginsight.atlassian.net/browse/BI-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1665 Store observations when importing new environments

src/main/java/org/breedinginsight/brapi/v2/model/request/query/ExperimentQuery.java, src/main/java/org/breedinginsight/utilities/response/mappers/ExperimentQueryMapper.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1548?atlOrigin=eyJpIjoiMDU3NTE2YWExOTFlNGMxZWJlOTA2N2Y2YWRhOWY3NDYiLCJwIjoiaiJ9
- Added createdBy and createDate experiment filtering
- bi-web BI-1548
- Test sorting and filtering for experiments CreatedBy and createDate
=> BI-1548 - Experiments: User and Creation Date Refinement

src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
**Story:** [BI-1129](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1129)
The germplasm processor was only checking for a possible empty value of the male pedigree parent. A check was put in place for the female parent as well.
bi-web: develop
Import germplasm where one of the accessions references a male parent but has a value of 0 entered for the gid of the female parent. Download the list and verify the contents of the download are correct.
[BI-1129]: https://breedinginsight.atlassian.net/browse/BI-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Check for empty pedigree female parent

src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/java/org/breedinginsight/utilities/response/mappers/GermplasmQueryMapper.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmTemplateMap.java
**Story:** [BI-1606](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1606)
Instead of using the list name(which may or may not be unique in the future) as the key for the mapping described in the card, a UUID is created for new lists and stored as an entry in the list's external references.
1. Updated Germplasm#constructBrAPIList to add a new external reference with referenceSource set to <BRAPI_BASE_URL>/lists and referenceId set to a randomly generated UUID. 
2. Updated Germplasm#constructBrAPIGermplasm(Program, BreedingMethodEntity, User, boolean, String, Supplier) to accept an argument of UUID germplasmListId
3. Updated Germplasm#constructBrAPIGermplasm(BreedingMethodEntity, User) to accept an argument of UUID germplasmListId
4. …
=> [BI-1606] Allow germplasm records to be in multiple lists

src/main/java/org/breedinginsight/api/model/v1/request/query/TraitsQuery.java, src/main/java/org/breedinginsight/api/v1/controller/TraitController.java, src/main/java/org/breedinginsight/utilities/response/mappers/TraitQueryMapper.java
**Story:** [BI-1629](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1629)
`TraitsQuery#constructSearchRequest` was created and called in the GET /traits controller of `TraitsController`.
The query params and search request are then passed to the same `ResponseUtils` method used by POST /traits for returning filtered traits.
none
call `GET /traits?<field>=<value>` using a searchable field for traits and verify only filtered traits returned.
[BI-1629]: https://breedinginsight.atlassian.net/browse/BI-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1629] Add filtering to Ontology Table

docker-compose.yml, src/main/java/org/breedinginsight/api/v1/controller/ProgramController.java, src/main/java/org/breedinginsight/services/geno/impl/GigwaGenotypeServiceImpl.java, src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java, src/test/java/org/breedinginsight/api/v1/controller/BreedingMethodControllerIntegrationTest.java, src/test/java/org/breedinginsight/brapi/v2/BrAPIV2ControllerIntegrationTest.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java, src/test/java/org/breedinginsight/services/geno/impl/GigwaGenotypeServiceImplIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1741
Updating how calls are fetched to prevent duplication of calls when there is more than one callset per germplasm
bi-web bug/BI-1741
brapi bug/BI-1741
Mgdb2BrapiV2Impl bug/BI-1741
Test using instructions from [BI-1650](https://breedinginsight.atlassian.net/browse/BI-1650)
[BI-1650]: https://breedinginsight.atlassian.net/browse/BI-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1741 - Genotype Import

src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/services/TraitUploadService.java, src/main/java/org/breedinginsight/services/parsers/ParsingExceptionType.java, src/main/java/org/breedinginsight/services/parsers/trait/TraitFileParser.java, src/main/java/org/breedinginsight/utilities/FileUtil.java, src/test/java/org/breedinginsight/utilities/response/FileUtilUnitTest.java
[BI-1583](https://breedinginsight.atlassian.net/browse/BI-1583) 
- For Germplasm and Experiment imports, 
+ add error banner message if the import XSL files does not have a workbook sheet titled "Data".  (to allow for backward compatibility also all allow the sheet to be titled "Germplasm Import" or "Experiment Data")
- For Ontology imports,
- Improve the error message.
- Show the error message if the import XSL files does not have a workbook sheet titled "Data".  (or, for backward compatibility  "Template")
bi-web branch **feature/BI-1583**
**Germplasm Import**
1. Create a valid Germplasm import XSL-file, with the date in a Worksheet titled "Data"
2. Import the file
**EXPECTED RESULT**
The validation is successful.
3. Create a valid Germplasm import XSL-file, with the date in a Workbook …
=> BI-1583 Error Message 1: Missing Data Worksheet

src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/test/java/org/breedinginsight/brapi/v2/GermplasmControllerIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1766
See story for details.
The endpoint `/v1/programs/{programId}/germplasm/lists/{listDbId}/records` was broken.
I fixed the bug and added a test for that endpoint.
=> [BI-1766] - Germplasm Lists details view fails to retrieve germplasm data

src/main/java/org/breedinginsight/api/v1/controller/BreedingMethodController.java, src/test/java/org/breedinginsight/api/v1/controller/BreedingMethodControllerIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1779
Updated controller method for enabling/disabling system breeding methods in a program to `DENY_ALL`
bi-web/bug/BI-1779
See bi-web#313
=> BI-1779 - Import germplasm with unspecified breeding method

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIListDAO.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPITrialDAO.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/model/response/ImportObjectState.java, src/main/java/org/breedinginsight/brapps/importer/model/response/PendingImportObject.java, src/main/java/org/breedinginsight/brapps/importer/services/ExternalReferenceSource.java, src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorData.java, src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java, src/test/java/org/breedinginsight/brapps/importer/ImportTestUtils.java
**Story:** [BI-1193](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1193)
Changes made to `ExperimentProcessor`:
- new field `obsVarDatasetByName` to hold a map for dataset pending import objects
- #getExistingBrAPIData--dataset pios for any existing trials set in the map
- #process--new datasets created and existing or new trial additionalInfo.observationDatasetId set; and additional obsvars added to existing dataset
- #post--new obsvars added to existing datasets and existing trials updated with additionalInfo
To handle the case when an import object needs to be updated the following were added:
- `ImportObjectState.MUTATED`
- `BrAPIDAOUtil#put`
- `ProcessorData#getMutationsByObjectId`
For updating Trials:
- …
=> [BI-1193] Associate phenotypes with experiment observation dataset

pom.xml, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/utilities/Utilities.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1778
- Added validations for matching location and year for all rows with same environment
- Also updated unit tests to cover this, and expanded unit test support to test for import preview in addition to import commit
none
Upload an experiment file with at least two rows for the same environment having the locations not match, and the years not match.  Ensure that error messages are shown for the location/year cells that are different than the first row.
=> BI-1778 - Environments locations and years

src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/services/ImportStatusService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorManager.java, src/main/java/org/breedinginsight/services/job/JobService.java, src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1689
There were 2 bugs causing the "Complete count" (a.k.a. finished count) to be less than the "Total count" on the jobs page:
1. The first bug was at the end of the `BrAPIDAOUtil.post` method where it was updating the finished count to be `listResult.size()`. The problem was that `listResult` contains all the BrAPI objects created during that call to `post`, but the finished count needs to account for BrAPI objects created during previous calls to `post`. I fixed this by using the local variable `finished` which is initially set to the current finished count (thus accounting for previous calls to `post`) and then incremented after each BrAPI call.
2. The object counts that are generated when a file is parsed, e.g. by …
=> [BI-1689] - Incorrect Jobs Count

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-1193](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1193)
The order that new Trials and dataset Lists are posted was changed from first-Trial-then-List to first-List-then-Trial to prevent the case where a network interruption would result in a Trial saved to the db containing a reference to a dataset List that was never created.
none
same as card and PR for BI-1193
[BI-1193]: https://breedinginsight.atlassian.net/browse/BI-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1193] addressed bug in BI-1193

src/main/resources/application.yml
Importing of experiments was failing during QA because the volume of data (for example, ~100,00 germplasm) was causing the time to refresh the phenotype materialized view after obs. unit creation to exceed the limit set in bi-api (10 minutes) when a timeout exception is thrown if it hasn't received a response from the brapi service.
The long-term solution is to update the Breedbase code to query the db directly instead of relying on mat. views.
The short-term solution here is to expose an environment variable that can be used to easily set the timeout value for bi-api. Then it can be adjusted as needed for different test or production environments.
breedinginsight/breedbase fork running bug/BI-1193 branch
_Please include any details needed for reviewers to test this code_
=> [BI-1193-2] BI-API throws timeout exception when BB mat view refresh exceeds 10m

src/main/java/org/breedinginsight/services/OntologyService.java
**Story:** [BI-1456](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1456)
`OntologyService::getSharedOntology` was updated to filter out from the list of sharable programs any programs currently sharing with each other.
none
- create three test programs A, B, and C
- import ontology into A and C but not B
- Have A share its ontology with B but do not have B accept
- Go to the Configuration tab of C and click "Share Ontology"
- verify that programs A is not present but B is present in the list of programs
- got to the configuration tab of B and accept sharing with A
- Go to the configuration tab of C and click "Share Ontology"
- verify neither A nor B are present in the list
[BI-1456]: …
=> [BI-1456] Ontology Share - Improvement

src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java, src/main/java/org/breedinginsight/brapps/importer/services/FileMappingUtil.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/LocationProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ObservationProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ObservationUnitProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/Processor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorManager.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/StudyProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/TrialProcessor.java
**Story:** [BI-1819](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1819)
A reference to the import upload was added to the signature of the interface method `Processor::process` so that the order of the dynamic columns in the import file can be used when creating a new observation dataset.
`TrialService::exportObservations` was updated to use the order of the names in the observation dataset obs var list returned from the brapi service when creating the dynamic columns for export.
none
1. using the deltabreed ui, upload an experiment containing multiple Observation Variable columns with or without observation data.
2. verify that the order of the obs var columns matches the order in the import file
3. import the experiment
4. go …
=> [BI-1819] Experimental download file: phenotypes are out of order

src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/services/TraitUploadService.java
[BI-1618 ](https://breedinginsight.atlassian.net/browse/BI-1618)- Import File Selection Behavior
Cleaned up the error message generated on the back-end.  Formatting and augmentation of the error messages will now happen on the front-end.
**bi-web:**  feature/BI-1618
see testing on [bi-web PR](https://github.com/Breeding-Insight/bi-web/pull/319)
- [] I have tested that my code works with both the brapi-java-server and BreedBase
- [] I have create/modified unit tests to cover this change
- [x ] I have commented my code, particularly in hard-to-understand areas
=> [BI-1618] Import File Selection Behavior

src/main/java/org/breedinginsight/brapps/importer/daos/BrAPITrialDAO.java, src/main/java/org/breedinginsight/brapps/importer/daos/impl/BrAPITrialDAOImpl.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java, src/test/java/org/breedinginsight/services/geno/impl/GigwaGenotypeServiceImplIntegrationTest.java
**Story:** [BI-1294](https://breedinginsight.atlassian.net/browse/BI-1294)
An instance of `ProgramCache` was added as a field in `BrAPITrialDAO` for caching experiments on the redis server. Methods in the DAO were updated to create,update, and read experiemnts from the cache. The program key was stripped from the trial name before storing in the cache.
none
Verify that experiment importing, exporting, and displaying of experiments in both group table and individual table still works as expected with lower latency.
[BI-1294]: https://breedinginsight.atlassian.net/browse/BI-1294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1294] Implement Caching Layer for Experiments

src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/services/ExternalReferenceSource.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1842
Loosened the validation of observations to only throw an error if a new upload will change the value of an existing observation.  If the incoming value is blank, then no validation error will be thrown.
None
1. Upload an experiment with observations
2. Upload a file to the same experiment with new observations to a different phenotype/trait.  Ensure that the observations from the first upload are blank in the second file
3. Ensure the file uploads successfully
1. Upload an experiment with observations
2. Upload a file to the same experiment with new observations to a different phenotype/trait.  Ensure that the observations from the first upload are copied from the first file to the second file
3. Ensure the file uploads …
=> BI-1842 - Append existing exp with observations isn't working

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationUnitDAO.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/test/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationUnitDAOTest.java
**Story:** [BI-1832](https://breedinginsight.atlassian.net/browse/BI-1832?atlOrigin=eyJpIjoiYjgyMDIwOGQxYTQxNDAyNzgzNmNmNDgxMDhmMTM1YmYiLCJwIjoiaiJ9)
- Storing treatments properly in Breedbase so that they are in the right spot to be reflected in the Breedbase UI was larger in scope than anticipated for this card so a new card was made to do that [BI-1850](https://breedinginsight.atlassian.net/browse/BI-1850?atlOrigin=eyJpIjoiZDY2NzFlNTYyNzg5NGJmMzg3MWU0ZjE3NmI5OWJmZWEiLCJwIjoiaiJ9)
- This card bi-api stores the treatments in additionalInfo and it will be saved in Breedbase through that mechanism and then bi-api populated the treatments property of the observation unit from the additional info data if the treatements property is empty
- sgn bug/BI-1832-2
- Import an experiment with …
=> BI-1832 - Treatment factors not being stored in BreedBase

src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
**Story:** [BI-1855](https://breedinginsight.atlassian.net/browse/BI-1855?atlOrigin=eyJpIjoiMmMzMzdmMjMyOGYzNDY4OGI5NjhjMDljNDc3MzAxMjEiLCJwIjoiaiJ9)
- Germplasm update logic changed:
- Allow empty pedigree values to enable creating a new germplasm list without requiring the original pedigree values
- Only require parent gids to be entered when updating a germplasm pedigree rather than gid and entry number
- Various bug fixes found when testing against Breedbase
- release/0.8 bi-web
- Test different combinations of updating pedigrees, synonyms, and not allowed pedigree changes
- Test files used in development, number indicates order ascending: [1855-tep46-np398.zip](https://github.com/Breeding-Insight/bi-api/files/12315658/1855-tep46-np398.zip)
[BI-1855]: …
=> BI-1855 - Create germplasm list not working

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationUnitDAO.java
[BI-1647](https://breedinginsight.atlassian.net/browse/BI-1647) (View Experiments: Observation Dataset Table)
Added the ability to retrieve the GID in the _additional information_ element of the Observation Unit.
bi-web: branch _feature/BI-1647_
see [bi-web PR](https://github.com/Breeding-Insight/bi-web/pull/322).
[BI-1647]: https://breedinginsight.atlassian.net/browse/BI-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1647] View Experiments: Observation Dataset Table

src/main/java/org/breedinginsight/api/v1/controller/TokenController.java, src/main/java/org/breedinginsight/brapi/v2/BrAPIV2Controller.java, src/test/java/org/breedinginsight/api/v1/controller/TokenControllerIntegrationTest.java, src/test/java/org/breedinginsight/brapi/v2/BrAPIV2ControllerIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1872
expanded the `TokenController#apiToken` method to allow the generation of a token to be triggered from the UI (previously this method was only used for generating a token for Field Book)
none
See https://github.com/Breeding-Insight/bi-web/pull/327
=> BI-1872 - Generate Access Token for using BrAPI with DeltaBreed

src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationUnitDAO.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/db/migration/V1_0_13__Update_BrAPI_Locations_XRefs.java, src/main/java/org/breedinginsight/db/migration/V1_0_15__Add_OU_Dataset_Xrefs.java, src/main/java/org/breedinginsight/utilities/Utilities.java
**Story:** [BI-1831](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1831)
The Experiment processor was changed so that new observation units created during experiment import have a dataset external ref assigned with the experiment observation dataset id set as the reference id.
A previous TODO was fulfilled by updating the BrAPITrialService::getDatasetData to use only OUs that have the corresponding dataset id as an exref.
A flyway migration was created to add dataset xrefs to existing observation units belonging to BI experiemnts.
NOTE: further bug fixes in breedbase are required in order to verify the migration occurred without error, so the verification is left commented out unilt that TODO is done in a separate card: …
=> [BI-1831] Add DatasetID to ObservationUnits

.env.template, docker-compose.yml, src/main/resources/application.yml
**Story:** https://breedinginsight.atlassian.net/browse/BI-1880
BreedBase refreshes materialized views after each POST request, so increasing the post-group-size from 100 to 1000 could reduce the number of refreshes and improve performance. I also added support for setting this value from a new environment variable `POST_CHUNK_SIZE` (added to .env.template).
I also snuck in some changes to docker-compose.yml which is helpful in development.
Upload large files, see if the chunk size is increased. The default value will be 1000 now, but you can also set a value in your .env.
Ultimately, once this is deployed we'll re-run the workflow documented on the Jira card to see if it's able to complete successfully.
=> BI-1880 - Error saving experiment import with Breedbase

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/test/java/org/breedinginsight/services/BrAPIGermplasmServiceUnitTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1881
Previously, `BrAPIGermplasmDAO::processGermplasmForDisplay` required parent `BrAPIGermplasm` objects to be available in order to add the `pedigreeByUUID` and `pedigreeByName` keys to `additionalInfo` on each `BrAPIGermplasm`. This required some hacks, [passing all germplasm in the program for example](https://github.com/Breeding-Insight/bi-api/blob/09ccfd5fa20dd199d7b00cd8f45516e3d2fa0b14/src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java#L295).
To make the code more efficient and avoid having to pass all program germplasm into `processGermplasmForDisplay`, I made changes to
- store male/female parent UUIDs on each `BrAPIGermplasm` in `additionalInfo` on create,
- read the parent UUIDs in …
=> BI-1881 - Store Parent UUIDs in Germplasm AdditionalInfo

src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java, src/test/java/org/breedinginsight/DatabaseTest.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1909
- Updated a unit test to check to prevent an NPE
- Updated unit tests so that the database and redis containers live between test suites
- Added some logging messages for fetching datasets
brapi-java-testserver/bug/BI-1909
Regression testing:
- experiment upload
- experiment view
- germplasm upload
- germplasm view
=> BI-1909 - Unable to open observation dataset. 

src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationUnitDAO.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1932
When dataset OUs the code was not fetching the GIDs.  Updated the `getObservationUnitsForDataset` method to fetch GIDs.
none
1. Import an experiment
2. Navigate to the experiment details page
3. Ensure that the GID column is populated for each row
=> BI-1932 - GIDs missing from Exp & Obs dataset

src/main/java/org/breedinginsight/api/v1/controller/OntologyController.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1340
> Previously, a user logged in as a system admin or a member of a breeding program could not see the sharing status on the Ontology list view (see Jira comments for more background). 
- Updated `getSubscribedOntology` (GET) endpoint authorization to allow read access to any authenticated user.
None
1. Upload Ontology to program A.
2. [Regression Test] Go to the program A Ontology list view as (1) system admin, (2) breeder, (3) member and ensure only the breeder role can edit Ontology Terms (expand a Term's detail view to try to edit).
3. Share program A's Ontology Terms with program B.
4. Accept the shared Ontology Terms in program B.
5. Go to the program B Ontology list view as (1) system admin, (2) breeder, (3) member and …
=> BI-1340 - Allow system admin, memeber roles to fully read Ontology 

src/main/java/org/breedinginsight/utilities/FileUtil.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1900
We parse Excel and CSV files into tablesaw `Table`s. For Excel files, we use Apache POI to parse, do some validation, and then build a `Table`. For CSV files, we were using tablesaw to read the CSV into a `Table` directly. While tablesaw does return descriptive error messages, it doesn't give us as fine-grained control over parsing and exception handling as we want. To solve this, I made changes to `FileUtil::parseTableFromCsv` to
- read the `InputStream` into a `String`, 
- parse the string with `apache.commons.CSVParser` and do validation, which enables us to return descriptive error messages *that we control* to the user, and
- finally build a `Table` from the `String`.
> Note: this only applies to Germplasm and Experiment …
=> BI-1900 - Exp error message improvement: unrecognized column header

src/test/java/org/breedinginsight/utilities/response/ResponseUtilsIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1943
The `ResponseUtilsIntegrationTest::postMultipleSearchSuccess` fails sporadically because the randomly seeded data could occasionally result in 2 records being returned from the search query instead of the expected 1.
The hardcoded value that is searched for is slope=1.1, so I changed the code to ensure that the randomly created slope values will never be 1.1 (`Math.random()` produces a number in the range [0,1)).
Run the `ResponseUtilsIntegrationTest` suite.
=> BI-1947 - fix non-deterministic test

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-1890](https://breedinginsight.atlassian.net/browse/BI-1890) - Experimental Test/Check Improvement
The main change was the addition of the method `validateTestOrCheck()`.  All of the other changes in the file where to address "problems" identified by InelliJ.  (the fist commit address the functionality, the second commit address the "problems".
bi-web: develop branch
Import an experiment with the values of the `Test (T) or Check (C)` column being a combination of:
- Valid Values - ['T', 'test' (any case combination), 'C', 'check'(any case combination), or \<BLANK\>]
- Invalid Values - [anything else (Examples: 'Tests', '(C)', 'bob']
**Expected Outcome**
One error message  for each invalid value, listed in the error table.
[BI-1890]: …
=> BI-1890 - Experimental Test/Check Improvement

src/main/java/org/breedinginsight/brapps/importer/services/FileMappingUtil.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-1930](https://breedinginsight.atlassian.net/browse/BI-1930) - trait names are case sensitive
When importing an experiment in the current system, the observation-variable must match an ontology in a case-sensitive way.  If not it will fail validation.  The purpose of this story is to allow the matching between the observation-variable and the ontology to be case-insensitive, while still allowing the observation-variable and the observation data to be saved correctly.  
bi-web: develop branch
WHEN An experiment is imported with observations.  
AND At least one observation-variable (i.e. the observation column header) differs from an ontology by case (for example: if the ontology is "Color" the observation-variable could be "cOLoR").  
**THEN The experiment should pass validation.**
WHEN …
=> [BI-1930] trait names are case sensitive

src/main/java/org/breedinginsight/brapps/importer/model/imports/BrAPIImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/MappingManager.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmFileImportTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1900
Because we'll need to provide different error messages for different import types, I moved the generic/default error messages to the `BrAPIImportService` abstract base class (thanks Tim!), and inheritors can override. 
- Updated an error message to match the source of truth.
- Updated unit tests.
See the comments on [the Jira story](https://breedinginsight.atlassian.net/browse/BI-1900) for more context.
bi-web/release/0.8.1
Test editing template-defined column headers in an experiment and observation file and uploading, ensure the displayed error message contains "Column heading does not match template or ontology". 
> Example: change "Exp Title" to "Experiment Title".
=> BI-1900 - Update Validation Error Messages

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-1911](https://breedinginsight.atlassian.net/browse/BI-1911) - in response to Shahana's [testing notes.](https://breedinginsight.atlassian.net/browse/BI-1911?focusedCommentId=14057)
bi-api: bug/BI-1911-2 branch
- Import an Experiment.
- Look at the confirmation page.
**Expected Results**
- The `Env Year`, `Env`, and  `Exp unit ID` columns should appear as they did in the import file.
[BI-1911]: https://breedinginsight.atlassian.net/browse/BI-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQescription
[BI-1911](https://breedinginsight.atlassian.net/browse/BI-1911) - in response to Shahana's [testing notes.](https://breedinginsight.atlassian.net/browse/BI-1911?focusedCommentId=14057)
bi-web: bug/BI-1911-2 branch
- Import an Experiment.
- …
=> BI-1911 fix QA findings

src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
[BI-1922](https://breedinginsight.atlassian.net/browse/BI-1922) Add ability to download all germplasm in a program
bi-web: feature/BI-1922
see test in [bi-web PR](https://github.com/Breeding-Insight/bi-web/pull/350)
[BI-1922]: https://breedinginsight.atlassian.net/browse/BI-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1922 (Add ability to download all germplasm in a program)

src/main/java/org/breedinginsight/api/v1/controller/TraitController.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/DataTypeTranslator.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/TermTypeTranslator.java, src/main/java/org/breedinginsight/services/OntologyService.java, src/main/java/org/breedinginsight/services/parsers/trait/TraitFileColumns.java, src/main/java/org/breedinginsight/services/parsers/trait/TraitFileParser.java
[BI-1915](https://breedinginsight.atlassian.net/browse/BI-1915) Export Ontology File
Additional work...
- The `Import file` option of the `Manage Ontology` pull-down is now only clickable for users that have the right to import.
- Addressed some of the preexisting code 'problems' reported by IntelleJ.
bi-web: feature/BI-1915
- Go to `Ontology` page.
- Select the `Download file` option from the `Manage Ontology` pull-down.
- Review the downloaded file;
. it should have a specified filename ( \<program name\>_ Active\_Ontology\_\<timestamp\> ).
. it should match the ontology template (including tags).
. it should include all of the active ontologies in the program.
. it should be in `Name` order.
[BI-1915]: https://breedinginsight.atlassian.net/browse/BI-1915?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
=> BI-1915 - Export Ontology File

docker-compose.yml
**Story:** https://breedinginsight.atlassian.net/browse/BI-1945
The bind mount wasn't overwriting the files in the container with the files on the host. I updated the paths to fix this, I guess trailing slashes don't have the desired effect for bind mounts.
=> [BI-1945-hotfix] - updated bind mount paths

src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/test/java/org/breedinginsight/services/validators/TraitValidatorUnitTest.java
**Story:**  [ BI-1867 - Ontology: Increase name length to 16 characters ](https://breedinginsight.atlassian.net/browse/BI-1867)
Modified backend logic and error text to increase the max permitted ontology name length from 12 to 16 characters.
[bi-web: feature/BI-1867](https://github.com/Breeding-Insight/bi-web/pull/354)
see bi-web
=> [BI-1867] - Ontology: Increase name length to 16 characters

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
**Story:** [BI-1960](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1960)
An additional check for multiple unique experiment titles in the same import file was put in place when creating the trial PIO during experiment import. An exception is thrown if multiple exp titles detected.
none
1. create an experiment import file containing multiple rows with at least two distinct experiment titles listed: for example, EXP-A and EXP-B.
2. attempt to import the experiments
A red error banner should appear citing "File contains more than one Experiment Title"
[BI-1960]: https://breedinginsight.atlassian.net/browse/BI-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1960-2] Exp import proceeds with multiple exp names & error message improvement

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationDAO.java, src/main/java/org/breedinginsight/brapps/importer/model/config/ImportFieldTypeEnum.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/BrAPIImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/ChangeLogEntry.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/germplasm/GermplasmImportService.java, src/main/java/org/breedinginsight/brapps/importer/model/imports/sample/SampleSubmissionImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/MappingManager.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/Processor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ProcessorManager.java, src/main/java/org/breedinginsight/utilities/Utilities.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
**Story:** [BI-1830](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1830)
The expected behavior of a user-supplied observation unit dbid superseding experiment, environment, and unit import values has apparently regressed. Fixing this regression will be handled in a separate card, and the parts of `ExperimentProcessor` involved commented out with TODOs. For this feature, observations are updated by filling out the complete import row with the ObsUnitID value blank.
1. Fields `overwrite` and `overwriteReason` added to `ExperimentObservation`
2. validation of existing observations updated
3. a `changeLog` entry is added to additionalInfo when committing updates to existing observations
4. `postBrapiData` was updated to both post new observations …
=> [BI-1830] Overwrite entity dataset

docker-compose.yml
**Story:** https://breedinginsight.atlassian.net/browse/BI-2019
Increased the shared memory size for the postgres container.
Related PR on bi-docker-stack: https://github.com/Breeding-Insight/bi-docker-stack/pull/38
**Verify Configuration Change**
- `docker exec -it bidb df -h | grep shm`
> Output will likely show the docker shared memory default of `64M`.
- `git checkout bug/BI-2019`
- `docker compose down`
- `docker compose up bidb brapi-server gigwa localstack mailhog mongo redis -d`
- `docker exec -it bidb df -h | grep shm`
> Output should show now `2.0G`.
=> BI-2019 - Pedigree Viewer Not Rendering

src/main/java/org/breedinginsight/daos/cache/ProgramCache.java, src/main/resources/version.properties
**Story:** https://breedinginsight.atlassian.net/browse/BI-2027
- Added cache key to all logs.
- Added a debug log for every call to `populate(UUID key)`.
None
None
=> BI-2027 - Add More Detailed Logging Around Redis Cache

docker-compose.yml, src/test/java/org/breedinginsight/services/geno/impl/GigwaGenotypeServiceImplIntegrationTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-1965
We have been using localstack/localstack:latest, and the env var we used, [EXTERNAL_HOSTNAME, is deprecated](https://github.com/localstack/localstack/blob/fe0d056cc7f5bb291e309485b4c244400385c6ad/localstack/config.py#L1188).
- Replaced with the supported LOCALSTACK_HOST env var. 
Related PR in bi-docker-stack: https://github.com/Breeding-Insight/bi-docker-stack/pull/37
> The error we were seeing with Gigwa not allowing imports from biapi
None
1. Functional Test:
- Checkout this branch `git checkout feature/BI-1965-bugfix`.
- Stop your local docker containers.
- Start your local docker containers. This will pick up the change.
- Run bi-api and bi-web.
- Ensure you can upload genotypic data (first upload …
=> [BI-1965-bugfix] - Fix Localstack And Gigwa Configurations

src/main/java/org/breedinginsight/brapps/importer/model/imports/experimentObservation/ExperimentObservation.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
**Story:** [BI-2028](https://breedinginsight.atlassian.net/browse/BI-2028)
During experiment import, existing germplasm dbid was being assigned to OU PIO by looking up the germplasm name stored in the OU PIO. When there are multiple germplasm with the same name, this was causing the same germplasm to be assigned to multiple OUs.
- Changed the OU PIO creation to include the germplasm GID as additional info
- mapped the germplasm to the OU PIO using the unique GID instead of the non-unique germplasm name
none
1. Import multiple germplasm with the same name
2. Import an experiment using GIDs from step 1.
3. After import successful, go to Experiment view and select the imported Experiment details
4. Verify that the correct GID is displayed.
See the card for sample import files.
[BI-2028]: …
=> [BI-2028] Duplicated accession names getting assigned duplicated GIDs after Exp&Obs upload

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
**Story:** [BI-1761](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1761)
updated the error message for missing observation unit ids in experiment file import.
none
run all tests in `ExperimentFileImportTest`
[BI-1761]: https://breedinginsight.atlassian.net/browse/BI-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1761] Error message with the backend code

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-2014](https://breedinginsight.atlassian.net/browse/BI-2014) - unable to download experiment
**Story:** IF an experiment was created; with at least one observation variable (ontology) that was missing a "Full Name",
THEN that experiment can not be downloaded.
NOTE: The issue of the Experiment's Phenotypes and Observations are not rendering in Experiment View has not been addressed in this code change.
Removed some code that was causing the observation variable to be saved without the [_program key_].  This code was originally added as defensive code that protected against legacy data.  That code may no longer be needed.
bi-web: develop 
1. Create an Ontology without a Full Name.
2. Create an Experiment with the Observation Variable defined in step 1.
3. Download the Experiment. …
=> BI-2014 - unable to download experiment

src/main/java/org/breedinginsight/brapi/v2/CropController.java, src/main/java/org/breedinginsight/brapi/v2/ProgramController.java, src/main/java/org/breedinginsight/utilities/response/ResponseUtils.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2038?atlOrigin=eyJpIjoiODdlMTQ1NmE4MjVhNDUxZWIxYzdkNGRhZjEyYjFjNDIiLCJwIjoiaiJ9
- Added brapi v2 endpoint overrides for /commoncropnames and /programs
- None
- Verify that /commoncropnames only returns the name of the crop for the programId in the path
- Verify that /programs only returns the program for the programId in the path and that the program key has been stripped from the name
=> BI-2038 BrAPI endpoint overrides for crops and programs to support MrBean

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
**Story:** [BI-1265](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1265)
During exp import processing, study season is fetched and assigned to additional info. The season value was being passed in as the season dbid and failing lookup in the database. The correct season value is now used.
Also, changes were made to avoid NPEs during update of brapi variables.
bi-web release/0.9
same as [BI-1830](https://github.com/Breeding-Insight/bi-api/pull/305) 
[BI-1265]: https://breedinginsight.atlassian.net/browse/BI-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-1830]: https://breedinginsight.atlassian.net/browse/BI-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
=> [BI-1265-2] Overwrite entity dataset

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
[BI-2045](https://breedinginsight.atlassian.net/browse/BI-2045) (Failure to report error when uploading duplicated experiment name)
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._
Successfully import an experiment.
Attempt to import the same experiment file (with no ObsUnitIDs).
**EXPECTED RESULT**
- The banner message `Error detected in file, XXX.xls. Experiment Title already exists. Import cannot proceed.`
[BI-2045]: https://breedinginsight.atlassian.net/browse/BI-2045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2045 (Failure to report error when uploading duplicated experiment name)

pom.xml, settings.xml, src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/services/writers/ExcelWriter.java, src/main/java/org/breedinginsight/utilities/FileUtil.java, src/test/java/org/breedinginsight/api/v1/controller/SampleSubmissionControllerIntegrationTest.java
**Story:** [BI-1993 - Accept NA Observations](https://breedinginsight.atlassian.net/browse/BI-1993)
Enables import of NA observations. Previously "NA" observations were set to blank on import due to default tablesaw behavior and "na" observations would be marked as invalid by validations for certain observation types.
Modify experiment import processing to skip observation ontology validations in the case where the entry is NA (case insensitive).
Modify pom/etc to utilize BI branch of tablesaw.
This utilizes a [BI fork of tablesaw](https://github.com/Breeding-Insight/tablesaw) created as a consequence of this card due to the need to remove NA from the inbuilt missingValueString list that automatically converts cells with values on the list to empty cells.
Create an experiment and multiple …
=> [BI-1993] - Accept NA observations

src/main/java/org/breedinginsight/brapps/importer/services/FileMappingUtil.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
**Story:** [BI-2046](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2046)
Validation errors are now returned for display in the experiment import preview for any rows referring to an existing environment and with the ObsUnitID blank.
bi-web release/0.9
Verify all tests pass in ExperimentFileImportTest
1) import an experiment with observations
2) download the exp data with ObsUnitId populated
3) select multiple observations for updating and change phenotype values
4) import and verify updates by viewing experiment details
[BI-2046]: https://breedinginsight.atlassian.net/browse/BI-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2046] Overwrite observations happening without reference to ObsUnitID

src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationUnitDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIStudyDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/impl/BrAPITrialDAOImpl.java, src/main/java/org/breedinginsight/daos/ObservationDAO.java, src/main/java/org/breedinginsight/utilities/FileUtil.java, src/test/java/org/breedinginsight/brapps/importer/daos/BrAPIObservationUnitDAOTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2058
Added Observations and ObservationUnits to the redis cache. They are eagerly fetched on application startup just like the other entities we cache. 
All the methods that **write** Observations or ObservationUnits have been modified to repopulate the cache, which is essential for reading one's own writes. 
Most of the methods that **read** Observations and Observation units have been modified to read from the cache.
>A few read methods still make BrAPI calls because it would be impractical to use the cache. For example, I did not update `BrAPIObservationUnitDAO::getObservationUnits` because some of the search parameters would be expensive to implement client-side (compared to SQL joins), notably the `seasonDbId` parameter, …
=> BI-2058 - Add Observations and ObservationUnits to Redis Cache

src/main/resources/db/migration/V1.21.0__remove_breeding_method.sql
**COPIED FROM https://github.com/Breeding-Insight/bi-api/pull/344**
**Story:** [BI-1680](https://breedinginsight.atlassian.net/browse/BI-1680)
Per the **Desired Behavior** section of the Jira story, I added a migration to remove the "Somoclone" breeding method from the system preset breeding methods.
This [bi-web PR](https://github.com/Breeding-Insight/bi-web/pull/370) takes care of updating the import template.
bi-web branch: `feature/BI-1680`.
1. Checkout this branch, `git checkout feature/BI-1680`.
2. Run bi-api.
3. Ensure that the new migration ran (~~V1.20.0~~ V1.21.0) by checking the bidb database, `SELECT * FROM flyway_schema_history;`.
4. Ensure that the "Somoclone" breeding method is not listed in the DeltaBreed UI, under **Program Administration > Breeding Methods**.
[BI-1680]: …
=> BI-1680 - Added Migration That Removes "Somoclone" Breeding Method

src/main/java/org/breedinginsight/services/TraitService.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/main/java/org/breedinginsight/utilities/Utilities.java, src/test/java/org/breedinginsight/api/v1/controller/TraitControllerIntegrationTest.java
Story: https://breedinginsight.atlassian.net/browse/BI-2053
These changes should have been done along with https://github.com/Breeding-Insight/bi-api/pull/331, but I missed the workflow where a user creates ontology terms one at a time by submitting the form on the DeltaBreed GUI. Please see [that original PR](https://github.com/Breeding-Insight/bi-api/pull/331#issue-2134480429) for rationale.
Corresponding PR on bi-web: https://github.com/Breeding-Insight/bi-api/pull/342.
bi-web branch: `bug/BI-2053-fix`
Ensure that traits of all types (Date, Ordinal, Nominal, Numerical, Text) can be created via form submission on the DeltaBreed GUI.
=> BI-2053-fix - Handled Trait Form Submission Code Path

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
[BI-2104](https://breedinginsight.atlassian.net/browse/BI-2104) - Can't create experiment with timestamped observations v0.9
There was a null pointer exception thrown in ExperimentProcessor.java at the line:
`priorStamp = existingObsByObsHash.get(observationHash).getObservationTimeStamp()`
Import a new experiment with observations (least one observation will need to have an associated time-stamp)
**Expected Result**
* Experiment should import sucessfully.
[BI-2104]: https://breedinginsight.atlassian.net/browse/BI-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2104] Can't create experiment with timestamped observations

.env.template, src/main/java/org/breedinginsight/services/UserService.java, src/main/java/org/breedinginsight/utilities/Utilities.java, src/main/java/org/breedinginsight/utilities/email/EmailUtil.java, src/main/resources/application.yml, src/main/resources/email/newAccountEmail.st
**Story:** https://breedinginsight.atlassian.net/browse/BI-2101
This PR enables bi-api to send transactional email using SMTP provided the `EMAIL_RELAY_HOST`, `EMAIL_RELAY_PORT`, `EMAIL_RELAY_LOGIN` and `EMAIL_RELAY_PASSWORD` are provided.
I configured DKIM and DMARC records required by SES so that we can send emails from noreply@breedinginsight.org.
I added an item to the [v0.10 Deploy Checklist](https://breedinginsight.atlassian.net/wiki/x/AQDLg) to update the production environment variables.
If the `EMAIL_RELAY_LOGIN` and `EMAIL_RELAY_PASSWORD` variables are omitted or empty, the code will continue to use SMTP without auth, which is desirable in development and non-production deployments.
___
1. javax.mail docs: https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summa …
=> BI-2101 - Configure Transactional Email for Production DeltaBreed

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2128
I implemented the desired behavior and updated tests.
Please reference [the story on Jira](https://breedinginsight.atlassian.net/browse/BI-2128).
=> BI-2128 - Blank cells overwriting existing observations

src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java
[BI-2127](https://breedinginsight.atlassian.net/browse/BI-2127) Position Information missing from exp download file
There were 2 separate problems:
1. The `row` and `column` fields would only populate if there was data for both `row` **and** `column`.  If a record only had data for `row` but not `column` or If a record only had data for `column` but not `row`, then the data for neither `row` or `column`would appear for that record.
2. The data for `Lat`, 'Long`, `Elevation`, and `RTK` was not being added to the download spreadsheet.
1. Import an experiment with `row` data but not `column` data.
2. Import an experiment with `column` data but not `row` data.
3. In the above two import files, include data for `Lat`, 'Long`, `Elevation`, and `RTK` 
4. Download the experiments
**EXPECTED …
=> BI-2127 Position Information missing from exp download file

src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/ExperimentUtilities.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/appendoverwrite/middleware/AppendOverwriteIDValidation.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/model/ExpImportProcessConstants.java
**Story:** [BI-2134](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2134)
The error message for the case of missing obs-unit ids for append workflow was changed to match the source of truth. A bug in writing the error message was fixed.
bi-web:develop
1. create an experiment
2. download experiment data
3. append data to the experiment download
4. delete one or more ids from the obs-unit-id column
5. import appended data
6. confirm the red error banner in the UI states "Required field is blank"
[BI-2134]: https://breedinginsight.atlassian.net/browse/BI-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix error message for missing obs unit id

src/main/java/org/breedinginsight/daos/ExperimentalCollaboratorDAO.java, src/main/java/org/breedinginsight/daos/ProgramUserDAO.java, src/main/java/org/breedinginsight/services/ExperimentalCollaboratorService.java, src/main/java/org/breedinginsight/services/ProgramUserService.java, src/test/java/org/breedinginsight/services/ExperimentalCollaboratorServiceTest.java, src/test/resources/sql/ExperimentalCollaboratorServiceTest.sql
**Story:** https://breedinginsight.atlassian.net/browse/BI-2257
- Implemented create, read and delete service (and when needed, DAO) methods for ExperimentalCollaborator. Keep in mind that the `ExperimentalCollaboratorService` and `ExperimentalCollaboratorDAO` are for interacting with the `experiment_program_user_role` table, they were named to make the purpose of this table obvious, rather than to make the connection to the table obvious.
- Updated the `ProgramUserService` and `ProgramUserDAO` methods to get a list of `ProgramUser` by role.
- Added tests for the new `ExperimentalCollaboratorService` methods.
> Note: An example of how to get the userId to pass down into the service method can be seen in `BreedingMethodController::createProgramBreedingMethod`. This is similar to how the …
=> BI-2257 - Experimental Collaborator DAO and Services for experimental_program_user_role

src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/ExperimentUtilities.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/appendoverwrite/factory/data/OverwrittenData.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/appendoverwrite/middleware/process/ImportTableProcess.java, src/main/java/org/breedinginsight/model/delta/DeltaEntity.java
**Story:** [BI-2134](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2134)
The cloning of entities via serializing-deserializing with Gson was producing an error if the instance being cloned contained nested classes that use the geogson library. The geometry type adapter was specified when building the gson instances to fix the error.
none
same test procedure as [BI-2134](https://github.com/Breeding-Insight/bi-api/pull/359)
[BI-2134]: https://breedinginsight.atlassian.net/browse/BI-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2134]: https://breedinginsight.atlassian.net/browse/BI-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2134 GeoGson Type Adapter Bug

src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/ExperimentUtilities.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/appendoverwrite/middleware/process/ImportTableProcess.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/service/ObservationUnitService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/service/ObservationVariableService.java
**Story:** [BI-2134](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2134)
When ontology variable names are used in append workflow import that do not exist in the system, the type of error thrown was not getting caught and message displayed on the front end. The type of error was changed to a more appropriate type, the old one added to the catch clause, and the message updated to match the source of truth.
none
same test procedure as [BI-2134](https://github.com/Breeding-Insight/bi-api/pull/359)
[BI-2134]: https://breedinginsight.atlassian.net/browse/BI-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2134]: https://breedinginsight.atlassian.net/browse/BI-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> BI-2134 Fix error message displayed for wrong observation variable headers

src/main/resources/db/migration/V1.27.0__fix_fk_constraint.sql, src/main/resources/version.properties
**Story:** [BI-2283](https://breedinginsight.atlassian.net/browse/BI-2283)
This migration gives the `experiment_program_user_role.program_user_role_id` foreign key constraint the `ON DELETE CASCADE` behavior. From the end user perspective, when a program user in the "Experimental Collaborator" role is assigned to a different role, this operation will not result in an error, and any record of the experiments they were given access to as an "Experimental Collaborator" will be lost.
> Because changing the role a program user is in results in a DELETE followed by an INSERT, changing a program user's role results in any associated rows in `experiment_program_user_role` being deleted once this migration is applied.
1. Run this migration.
2. If it hasn't been merged into develop yet, check out …
=> BI-2283 - Modify the experiment_program_user_role.program_user_role_id FK to use ON DELETE CASCADE

src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
[BI-2267](https://breedinginsight.atlassian.net/browse/BI-2267) Trim trailing white space on breeding method file uploads
When importing germplasm, if there was a trailing blank in a _breeding method_ value, then the system was generating the table error  `Invalid breeding method`.
This fix removes any leading and trailing spaces in the imported _breeding method_ values.
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._
1. Import a germplasm file with a trailing blanks in some of the _breeding method_ field.  You can use [ABC_germplasm_2024-08-02_06-20-46+0000import.xlsx](https://github.com/user-attachments/files/16697377/ABC_germplasm_2024-08-02_06-20-46%2B0000import.xlsx) which has trailing blanks in every _breeding method_ with …
=> [BI-2267] Trim trailing white space on breeding method file uploads

src/main/java/org/breedinginsight/api/v1/controller/ExperimentController.java
**Story:** [BI-2295 - Allow Experimental Collaborators To View Collaborators](https://breedinginsight.atlassian.net/browse/BI-2295)
Changed permissions for GET collaborators endpoint to enable Read Only and Experimental Collaborators to access the endpoint so they can view collaborators on an experiment.
bi-web: [feature/BI-2295](https://github.com/Breeding-Insight/bi-web/pull/397)
see bi-web
=> [BI-2295] - Allow Experimental Collaborators To View Collaborators

src/main/java/org/breedinginsight/daos/impl/BreedingMethodDAOImpl.java, src/main/resources/db/migration/V1.29.0__remove_blank_from_breeding_method.sql
[BI-2267 ](https://breedinginsight.atlassian.net/browse/BI-2267)Trim trailing white space on breeding method file uploads (FAILED QA)
IF the he **Breeding Method** field in the germplasm import file has the value "Bulk or population " (with a trailing blank),
THEN the import fails with an erroneous "Invalid Breeding Method" error.
- The **Breeding Method** field in the germplasm import file must match the `name` column in the `breeding_method` table _exactly_.
- One entry in the `breeding_method` table has a trailing blank in the `name` column; "Bulk or population ".
- The new code for [BI-2267 ](https://breedinginsight.atlassian.net/browse/BI-2267) trims the white space off of the value for the **Breeding Method** field in the germplasm import file.
- this causes an erroneous "Invalid …
=> [BI-2267]Trim trailing white space on breeding method file uploads (FAILED QA)

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/ExperimentUtilities.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/create/workflow/steps/ValidatePendingImportObjectsStep.java
**Story:** [BI-2310 - Exp import: extraneous error message](https://breedinginsight.atlassian.net/browse/BI-2310)
Fix to prevent duplicate errors appearing on experiment import when the Exp Unit Id was missing that was due to the code treating <environment name> + null as a valid unique environment-expunitid combo.
n/a
Try to import an experiment file with a missing Exp Unit Id
In errors table should see for corresponding row and field combo a "Field is blank when creating a new experiment." error
And should NOT see a secondary "not unique within the environment" error
Also good to try the missing Env case and a valid file case
=> [BI-2310] - Exp import: extraneous error message

src/main/java/org/breedinginsight/brapi/v2/BrAPIStudiesController.java, src/main/java/org/breedinginsight/brapi/v2/BrAPITrialsController.java, src/main/java/org/breedinginsight/services/ProgramUserService.java
**Story:** [BI-2317](https://breedinginsight.atlassian.net/browse/BI-2317)
This pull request removes a check when fetching collaborators that throws an exception if the user is not a program user. This check was causing problems for system users like sys admins that have access to a program. It refactors code in three files to improve error handling, optimize data retrieval, and enhance code clarity. 
- In BrAPIStudiesController.java, unnecessary exception handling for DoesNotExistException is removed. 
- BrAPITrialsController.java is restructured to streamline the process of fetching experiments, with improved handling for experimental collaborators and more efficient use of Optional. 
- ProgramUserService.java is refactored to simplify the getIfExperimentalCollaborator method using …
=> [BI-2317] System Admin Must Retain Full Read Access To All Programs

src/main/java/org/breedinginsight/brapi/v2/constants/BrAPIAdditionalInfoFields.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/java/org/breedinginsight/utilities/response/mappers/GermplasmQueryMapper.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmFileImportTest.java, src/test/resources/files/germplasm_import/new_and_existing_list_entries.csv, src/test/resources/files/germplasm_import/valid_duplicate_entries.csv
**Story:** https://breedinginsight.atlassian.net/browse/BI-2304
- Removed `listEntryNumbers` additional info field.
- Used BrAPI list ordering to assign sequential entry numbers for display (including preview) and export of germplasm lists (instead of `listEntryNumbers`). The `importEntryNumber` additional info field is used for display purposes, i.e. it is set (or overwritten) based on the BrAPI list item ordering as germplasm records are processed for display. In this way, it can be used without issue for the same germplasm record in different positions in multiple lists or even the same list (in the case of duplicate entry).
- Used deep copy (the serialize and deserialize technique in `GermplasmProcessor::processExistingGermplasm` and `BrAPIGermplasmService::cloneBrAPIGermplasm` to …
=> BI-2304 - Support Duplicate Germplasm in Lists Referencing Existing Germplasm

src/main/java/org/breedinginsight/brapi/v2/BrAPIPedigreeController.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIPedigreeDAO.java
**Story:** [BI-2306](https://breedinginsight.atlassian.net/browse/BI-2306?atlOrigin=eyJpIjoiNmY0ZDE4ODk3ZWNiNGQzZGFmYmQwM2RhMjVlZTdiYzciLCJwIjoiaiJ9)
- Added query parameter for accessionNumber
- None
- Load data in Helium (https://helium.hutton.ac.uk) via BrAPI and filter by accessionNumber
- Verify get data for that germplasm and loading time is acceptable in program with large amount of germplasm
[BI-2306]: https://breedinginsight.atlassian.net/browse/BI-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2306 - Helium BrAPI integration filter by accessionNumber 

src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorErrorInterface.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/test/java/org/breedinginsight/model/delta/DeltaEntityFactoryUnitTest.java, src/test/java/org/breedinginsight/services/validators/TraitValidatorUnitTest.java
[BI-2328](https://breedinginsight.atlassian.net/browse/BI-2328) Experimental observation file import removes periods from column headers
Added a validation so that a user can no longer add an ontology term with a period (.) in the Name field. 
bi-web: **bug/BI-2328**
**Test 1 (Manually add Ontology)**
1. Given user is logged in the application as a Program Administrator
2. Given user has selected an appropriate program (one in which they are a Program Administrator).
3. WHEN user selects "Ontology" in navigation
4. AND user selects 'New Term' button on ontology list page
5. AND user enters a text value with a period ('.') into the 'Name' field
6. AND user selects 'Save' button
7. THEN an error banner will appear with the text "Period in name is invalid"
8. AND the error message  "Period …
=> [BI-2328] Experimental observation file import removes periods from column headers

src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2344
I introduced this regression in [BI-2304](https://breedinginsight.atlassian.net/browse/BI-2304).
Because germplasm names are not guaranteed to be unique within a program or list, code that used germplasm name as a key for lookups had unexpected behavior in the case of multiple distinct germplasm in a list that shared the same name (different GIDs, same name is allowed).
The solution was to use the "{germplasmName} [{programKey}-{accessionNumber}]" format as the key for lookups instead, which is what is stored in the backing BrAPI service. Finally, the program key and accession number are stripped from the germplasm name when building the output file data (we don't want to display that to the user).
1. Upload a germplasm file …
=> BI-2344 - Incorrect Germplasm Export in Case of Duplicate Germplasm Names

src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorErrorInterface.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java, src/test/java/org/breedinginsight/services/validators/TraitValidatorUnitTest.java
[BI-2328](https://breedinginsight.atlassian.net/browse/BI-2328) Experimental observation file import removes periods from column headers
The [previous pull request](https://github.com/Breeding-Insight/bi-api/pull/411) passed but was branched off of the 'develop' branch instead of the  'release/1.0' branch.  This PR fixes that.
bi-web: bug/[BI-2328](https://breedinginsight.atlassian.net/browse/BI-2328)
See the [previous pull request](https://github.com/Breeding-Insight/bi-api/pull/411)
[BI-2328]: https://breedinginsight.atlassian.net/browse/BI-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2328]: https://breedinginsight.atlassian.net/browse/BI-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> BI-2328 Failed QA

src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/services/validators/TraitFileValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorError.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorErrorInterface.java, src/main/java/org/breedinginsight/services/validators/TraitValidatorService.java
(New branch due to soiled changelist in previous attempt)
**Story:**  [BI-2355 - Non-informative error message: regression](https://breedinginsight.atlassian.net/browse/BI-2355)
This error was due to tablesaw processing brackets weirdly, resulting in the column name stored in data not matching the column name stored in dynamic column names. This was fixed in two parts:
1) Removing brackets from ontology term names on upload
2) Preventing ontology terms with brackets in the name from being created by extending the functionality created in BI-2328
Note that this means for the error message re ontology terms not found, periods and brackets will be removed from the invalid ontology term names
bi-web: [bug/BI-2355.2](https://github.com/Breeding-Insight/bi-web/pull/412)
Test that on upload of …
=> [BI-2355] - Non-informative error message: regression

src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/services/ExperimentValidateService.java, src/main/java/org/breedinginsight/utilities/Utilities.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2354
- Made the code that collects invalid ontology terms for the error message do a case-insensitive contains (thanks Nick for the utility method).
- Modified aforementioned `containsCaseInsensitive` utility method to work on any `Collection<String>` so I could use it on a `Set<String>` as well as a `List<String>`.
- The second place I updated the code to be case-insensitive (in ExperimentProcessor.java) seems to be unused, but I updated the logic in case it is ever used again.
1. Import germplasm: [100_germplasm_QUICK.csv](https://github.com/user-attachments/files/17576845/100_germplasm_QUICK.csv).
2. Import ontology: [R2D2_Active_Ontology_2024-10-30_04-56-59+0000.xlsx](https://github.com/user-attachments/files/17576849/R2D2_Acti …
=> [BI-2354] - Incorrect Case Sensitivity in Exp Import Error Message

src/main/java/org/breedinginsight/utilities/FileUtil.java
**Story:** [BI-2338](https://breedinginsight.atlassian.net/browse/BI-2338?atlOrigin=eyJpIjoiMTRlYjM1YzkwYzFjNGZlZjkwNzJhNzI3NDZjODM2ZTMiLCJwIjoiaiJ9)
- Trim values in Excel file import flow
An additional [card](https://breedinginsight.atlassian.net/browse/BI-2366?atlOrigin=eyJpIjoiODA3ZTExNjVhZmM1NDA4ZDkxMmMwNjQ5NTE0OWQxOWIiLCJwIjoiaiJ9) was made for inclusion in a post MVP release to either not allow '[]' in germplasm names or only strip off the rightmost occurrence of them from names.
- None
- Ensure Germplasm import file with germplasm names containing trailing whitespace can be imported and downloaded without issue
[BI-2338]: https://breedinginsight.atlassian.net/browse/BI-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2338 - Germplasm file with problems is loading, but preventing download

src/main/resources/brapi/sql/R__species.sql, src/main/resources/db/migration/V1.31.0__update_species_honey.sql
**Story:** [BI-2365](https://breedinginsight.atlassian.net/browse/BI-2365?atlOrigin=eyJpIjoiZWU3MjEyNjE2ZjEwNDhhMDkxOWI0NTc1MDE1ZDVkYjciLCJwIjoiaiJ9)
- Renamed Honey to Honey Bee
- bi-web release/1.0
- Verify Honey Bee is in the species select box when creating a program
- Create a Honey Bee program and verify it is created without error
[BI-2365]: https://breedinginsight.atlassian.net/browse/BI-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2365 - BI-2365 Change Honey to Honey Bee under program Species list

src/main/java/org/breedinginsight/brapps/importer/services/FileImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/DynamicColumnParser.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/appendoverwrite/middleware/process/ImportTableProcess.java
[BI-2328](https://breedinginsight.atlassian.net/browse/BI-2328) Experimental observation file import removes periods from column headers
[BI-2355](https://breedinginsight.atlassian.net/browse/BI-2355) Non-informative error message: regression
If the user attempts to import an experiment with periods or square brackets in the observation headings.  The user will get an error.
[BI-2328]: https://breedinginsight.atlassian.net/browse/BI-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2355]: https://breedinginsight.atlassian.net/browse/BI-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2328 and BI-2355 failed QA

src/main/java/org/breedinginsight/db/migration/V1_32_0__Set_Dev_Admin_Email.java
**Story:** The original story was https://breedinginsight.atlassian.net/browse/BI-2203, this is just a fix to change the name to a version that doesn't conflict with another migration that was added in the release/1.0 branch, [see here](https://github.com/Breeding-Insight/bi-api/blob/main/src/main/resources/db/migration/V1.31.0__update_species_honey.sql).
> This change will break local and test environments, but, critically, it won't break production.
=> BI-2203-bugfix - Renamed Conflicting Migration

pom.xml
**Story:** [BI-2156](https://breedinginsight.atlassian.net/browse/BI-2156)
- Upgraded apache tika to 2.9.2.
- Removed as many hard-coded transitive dependencies as possible.
- Hard-coded transitive dependency apache commons compress, because some tests were failing without specifying a compatible version.
**You may need to do a maven `clean install`.**
- Test uploading files, verify no unexpected errors.
- Ensure tests pass.
[BI-2156]: https://breedinginsight.atlassian.net/browse/BI-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2156 - Upgrade Apache Tika to 2.3.0+

src/main/java/org/breedinginsight/utilities/response/ResponseUtils.java
**Story:** [BI-2343 - GID filtering not informative](https://breedinginsight.atlassian.net/browse/BI-2343)
Changes to enable exact match GID filtering for multiple tables
For Experiment Details and Sample Submission Details tables, frontend search is used, so a custom-search function was added in the respective buefy files to do exact search filtering in the GID case.
For Germplasm and Germplasm list tables, backend search is used, which presently only does partial matching. Due to the high risk associated with modifying backend search to alternatively enable exact or partial match for each filter, ResponseUtils:search was slightly modified to do an exact match specifically when the filter is accessionNumber.
[bi-web: bug/BI-2343](https://github.com/Breeding-Insight/bi-web/pull/418)
see …
=> [BI-2343] - GID filtering not informative

src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/appendoverwrite/factory/entity/PendingObservationUnit.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/service/ObservationUnitService.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2424
I updated several places where Observation Unit IDs were referred to as Experimental Unit IDs.
No testable changes, this PR only renames things.
=> BI-2424 - Refactor getObservationUnitsByDbId for clarity

src/main/java/org/breedinginsight/api/v1/controller/ExperimentController.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPICachedDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIListDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationUnitDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIStudyDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPITrialDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/impl/BrAPITrialDAOImpl.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIListService.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPITrialService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/create/workflow/steps/PopulateExistingPendingImportObjectsStep.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/experiment/service/DatasetService.java, src/main/resources/version.properties, src/test/java/org/breedinginsight/api/v1/controller/ExperimentControllerIntegrationTest.java
**Story:** [BI-2376](https://breedinginsight.atlassian.net/browse/BI-2376)
This feature adds a delete endpoint for experiments to bi-api. The endpoint is capable of requesting a hard or soft delete of the backing brapi service, but if an experiment has observations and a hard delete is requested, nothing will be deleted and a 409 Conflict response will be returned.
Additional features:
- Cache invalidation for all affected entities: trial, study, observation and observation unit (using an inefficient but effective full-key repopulation method).
- Uses the `BrAPIListDAO::deleteBrAPIList` method to delete all lists along with the experiment.
- Renamed several Lists methods for clarity.
Now that https://github.com/Breeding-Insight/brapi-Java-TestServer/pull/41 has been merged, the delete …
=> BI-2376 - Create Delete Endpoint for Deltabreed Experiment Controller

src/main/java/org/breedinginsight/api/v1/controller/geno/SampleSubmissionController.java, src/main/java/org/breedinginsight/brapi/v2/dao/impl/BrAPITrialDAOImpl.java, src/main/java/org/breedinginsight/brapps/importer/daos/BrAPISampleDAO.java, src/main/java/org/breedinginsight/model/SampleSubmission.java, src/main/java/org/breedinginsight/services/SampleSubmissionService.java, src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java, src/test/java/org/breedinginsight/brapi/v2/ListControllerIntegrationTest.java
**Story:** [BI-2379](https://breedinginsight.atlassian.net/browse/BI-2379?atlOrigin=eyJpIjoiYTM1NzFmNzRhNTU1NDA3ZGI1YjFlNGY4YjFkMmZhMTUiLCJwIjoiaiJ9)
- Added endpoint in bi-api for deleting a sample submission
- bi-web feature/BI-2380 & brapi-server feature/BI-2431
- Upload Germplasm: [Test file](https://github.com/user-attachments/files/18442773/bi_germplasm_import_template_v11.xls)
- Upload sample submission [Test file](https://github.com/user-attachments/files/18442787/bi_sample_submission_template_v01.xls)
Change submission status in UI as needed to test different acceptance criteria as listed below:
GIVEN a DELETE programs/{programId}/submissions/{submissionId} request
WHEN the sample submission specified has a submission status of NOT SUBMITTED 
THEN the sample submission is deleted …
=> BI-2379 - Create Delete Endpoint for Deltabreed Sample Controller

src/main/java/org/breedinginsight/brapi/v2/BrAPIObservationsController.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationDAO.java, src/main/java/org/breedinginsight/services/TraitService.java, src/test/java/org/breedinginsight/brapi/v2/BrAPIObservationsControllerIntegrationTest.java
**Story:** [BI-2047](https://breedinginsight.atlassian.net/browse/BI-2047)
Partially implemented the BrAPI /observations GET endpoint to support pulling existing observation values into Field Book. The endpoint only supports `studyDbId` and pagination (`pageSize`, `page`) query parameters. The use of other query parameters will result in a `501 Not Implemented` response. The use of invalid ***pagination*** query parameters will result in a `400 Bad Request` response.
**Valid pagination query parameters must satisfy the following conditions.**
- ~~Either both or neither of `page` and `pageSize` must be present, one is invalid without the other.~~ (BrAPI specifies default values).
- If present, `pageSize` must be greater than zero. If omitted, `pageSize` defaults to `1000`.
- If present, …
=> BI-2047 - Pull Existing Observation Values For An Experiment Into Field-Book

.env.template, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIObservationUnitDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIStudyDAO.java, src/main/java/org/breedinginsight/brapi/v2/dao/impl/BrAPITrialDAOImpl.java, src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java, src/main/resources/application.yml
[BI-2450](https://breedinginsight.atlassian.net/browse/BI-2450) - BrAPI Server DB connections exhausted on biapi startup caching
The scheduled delay in creating the cache from the  DOA's is now driven by the .env file.  That way the expensive calls to the BrAPI server (that are called when bi-api is first started). can be staggered.  The timing can be changed in a config file (.env), so that it can be fine tuned in each environment.  
- If the new parameters are NOT added to your local .env-file then there should be no change to the system's behavior.
- If the new parameters are added, then the caching should be scheduled accordingly.  
- FOR EXAMPLE:
- if the parameters are:
- `germplasm_start_delay=5s
study_start_delay=10s
trial_start_delay=15s
trait_start_delay=20s …
=> [BI-2450]BrAPI Server DB connections exhausted on biapi startup caching

src/main/resources/brapi/sql/R__create_indexes.sql, src/test/resources/sql/brapi/mount/R__create_indexes.sql
[BI-2585](https://breedinginsight.atlassian.net/browse/BI-2585) BJTS migration fail due to DB field name change
**Action taken**
updated 'connceted_node_id' to 'connected_node_id'
[BI-2585]: https://breedinginsight.atlassian.net/browse/BI-2585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2585] BJTS migration fail due to DB field name change

src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
[BI-2187](https://breedinginsight.atlassian.net/browse/BI-2187) Non-sequential GIDs After Circular Dependency Error
bi_web: develop
1. Try to import the following Germplasm file [Circ ped.xls](https://github.com/user-attachments/files/18948669/Circ.ped.xls)
2. EXPECTED RESULT:  it will fail on “Validate & Upload” due to circular dependency.  
3. Next, import the following Germplasm file [No Circ ped.xls](https://github.com/user-attachments/files/18966019/No.Circ.ped.xls)
4.  EXPECTED RESULT:   it will succeed.
5. Navigate to the Germplasm list view
6. EXPECTED RESULT:   There will be no gap in the GID sequence
[BI-2187]: https://breedinginsight.atlassian.net/browse/BI-2187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2187] Non-sequential GIDs After Circular Dependency Error

src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmFileImportTest.java, src/test/resources/files/germplasm_import/entry_no_asc.csv, src/test/resources/files/germplasm_import/entry_no_desc.csv
**Story:** [BI-2573](https://breedinginsight.atlassian.net/browse/BI-2573?atlOrigin=eyJpIjoiYjdhOWM5YmQ4NWNhNDUxYmI1ZGY0YWI0YmFmNjM2NmIiLCJwIjoiaiJ9)
- Sorted germplasm records by entry number at entry point of processor so all processing was done consistently in entry number order
- Added automated tests to validate correct pedigree assignment regardless of entry number order in the import file
- develop branch on other repos
- Verify that germplasm files with entry numbers any order besides entry number ascending with pedigree import without a circular dependency error if there is no circular dependency in the pedigree connections. Also verify that the germplasm records have the correct pedigree information assigned.
Some test files are available that resulted in incorrect circular …
=> BI-2573 Germplasm file import assigns pedigree incorrectly

src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/brapi/v2/services/BrAPIListService.java
BI-2567 - Germplasm Lists Tab Slow to Load
The Germplasm List Screen and the "Details" Screen for a germplasm list both take too long to load if a germplasm list has (30,000 or more germplasm).  
To fix the the slow Germplasm List Screen, the BrAPIListService::getListSummariesByTypeAndXref() was rewritten to load every germplasm only once (as opposed to once per germplasm list).
To fix the slow "Details" Screen, the BrAPIGermplasmService::getGermplasmByList was modified to remove an unnecessary loop inside a loop.
GIVEN several germplasm list have been imported (3 or more list).
GIVEN at least one of the germplasm list is large (30,000 or more germplasm).
WHEN the user navigates to the `Germplasm` screen.
AND WHEN the user selects the `List` tab.
THEN the Germplasm List Screen should be …
=> BI-2567 - Germplasm Lists Tab Slow to Load

src/main/java/org/breedinginsight/brapps/importer/model/imports/germplasm/GermplasmImportService.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/germplasm/GermplasmImportIdUtils.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/germplasm/GermplasmProcessor.java, src/test/java/org/breedinginsight/brapps/importer/GermplasmFileImportTest.java, src/test/resources/files/germplasm_import/duplicate_names_circular_dependency.csv
**Story:** [BI-2593](https://breedinginsight.atlassian.net/browse/BI-2593?atlOrigin=eyJpIjoiODFmZTA2YjI4ZTI3NGFmZWFlNDBmNzBiM2NjYzdhODEiLCJwIjoiaiJ9)
- Updated so that germplasm id references are unique for both preview and commit phases of postOrder
- develop bi-web
- Ensure that files with duplicate names and pedigree work and that there are no regressions. Example test file:
[Pecan Import All Germplasm Renamed.xlsx](https://github.com/user-attachments/files/19652629/Pecan.Import.All.Germplasm.Renamed.xlsx)
[BI-2593]: https://breedinginsight.atlassian.net/browse/BI-2593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2593 - Circular Dependency False Positive Error

src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java, src/main/java/org/breedinginsight/utilities/Utilities.java
**Story:** [BI-2594](https://breedinginsight.atlassian.net/browse/BI-2594?atlOrigin=eyJpIjoiMDY1OGFjZTgwYTU4NDU1YjgyZWI5ZjIyNzgxOTU3ZGEiLCJwIjoiaiJ9)
- Switched to using gids instead of germplasm names for tracking germplasm
- release/1.1 bi-web
- Import a germplasm file with duplicate names and pedigree. Verify that the germplasm list table shows the data in agreement with the file
[BI-2594]: https://breedinginsight.atlassian.net/browse/BI-2594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2594 - Germplasm list table wrong when duplicate names are included

src/main/java/org/breedinginsight/services/UserService.java, src/main/java/org/breedinginsight/utilities/email/EmailUtil.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2595
This PR is to add logging to email sending to troubleshoot on rel-test, as I cannot reproduce locally.
=> [BI-2595 - LOGGING] - Regression: Transactional Email IOException

.env.template, src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java, src/main/resources/application.yml, src/main/resources/brapi/properties/application.properties, src/test/java/org/breedinginsight/daos/BrAPIDAOUtilUnitTest.java, src/test/java/org/breedinginsight/services/BrAPIGermplasmServiceUnitTest.java, src/test/java/org/breedinginsight/services/geno/impl/GigwaGenotypeServiceImplIntegrationTest.java
[BI-2578](https://breedinginsight.atlassian.net/browse/BI-2578)
* Updated the `BrAPIGermplasmDAO` and the `BrAPIDAOUtil` to fetch all existing germplasm records at once for a program, without pagination.  This will allow the BrAPI server to handle the request and it will resolve [BI-2489](https://breedinginsight.atlassian.net/browse/BI-2489) for Germplasm cache fetches.  This feature is configurable via the new `CACHE_PAGINATE_GERMPLASM` env var, added to the template and application.yml.  If the memory gets exhausted for a particular programs germplasm records, this var should be = `true`.
* Updated the BrAPIDAOUtil so that for all other entities, it fetches the cache 65000 records at a time to potentially avoid any other SQL errors that could come up as a result of BI-2489.  If this …
=> [BI-2578][BI-2489] - Optimize BrAPI Germplasm Search 

pom.xml
**Story:** [BI-2595](https://breedinginsight.atlassian.net/browse/BI-2595)
The apache Tika upgrade broke email sending, unclear exactly why. I reverted that change, [BI-2156](https://breedinginsight.atlassian.net/browse/BI-2156) ([PR](https://github.com/Breeding-Insight/bi-api/pull/432)).
⚠️ I recommend hiding whitespace changes when reviewing pom.xml.
Must run with bi-docker-stack.
Test transactional email sending (either with SES or mailhog) when running with bi-docker-stack. Ensure email sends successfully.
[BI-2595]: https://breedinginsight.atlassian.net/browse/BI-2595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2156]: https://breedinginsight.atlassian.net/browse/BI-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> BI-2595 - Regression: Transactional Email IOException

src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java, src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java, src/main/resources/brapi/properties/application.properties
**Story:**[ BI-2579](https://breedinginsight.atlassian.net/browse/BI-2579)
To optimize the importing experience for germs, I've changed the code so that the cache only refreshes one time during the import process, at the end.
This idea of posting and refresing the cache from the response of a batch chunk being imported confuses me.  Why would we not just refresh at the end of the process, or, since the cache refreshes everytime you view germplasm, is it done at all?
Maybe someone here can tell me a little bit more, but, when disabling this refreshing process, I found the performance of the import drastically improves. This is another problem that would also not exist if the cache were removed entirely and replaced with paginated requests for the data that needs to be viewed, but this can …
=> [BI-2579] Refresh cache after import completes

docker-compose.yml, src/test/java/org/breedinginsight/DatabaseTest.java
**Story:** https://breedinginsight.atlassian.net/browse/BI-2212
Update the postgres version to 17.
This change will affect local and the changes to bi-docker-stack ([PR here](https://github.com/Breeding-Insight/bi-docker-stack/pull/56)) will affect qa-test, but not rel-test or production, which use RDS (those are a separate task).
> Note that our CI already uses the `postgres:latest` image (see .github/workflows/build.yml for example).
None
Running this without existing data will work without issues.
To upgrade data locally, you can use `pg_dump` with the old database and then restore to the new postgres instance, but unless you really need that data locally, it's probably not worth it.
The upgrade for rel-test and production will be similar to the process I described, but slightly …
=> BI-2212 - Update Postgres Version
